/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Clases;

import java.awt.CardLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author cesar
 */
public class Interfaz extends javax.swing.JFrame {
    
    private ArrayList<Animal> listaAnimales;
    /**
     * Creates new form Interfaz
     */
    public Interfaz() {
        initComponents();
        this.listaAnimales = listaAnimales;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        PanelLiberacion = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        TextFieldID2 = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jTextField9 = new javax.swing.JTextField();
        jSeparator5 = new javax.swing.JSeparator();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jTextField15 = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jSeparator6 = new javax.swing.JSeparator();
        PanelDeFondoGlobal = new javax.swing.JPanel();
        PanelDelMenu = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        BotonAlta = new javax.swing.JButton();
        BotonSalir = new javax.swing.JButton();
        BotonBaja = new javax.swing.JButton();
        BotonTratamiento = new javax.swing.JButton();
        BotonLiberacion = new javax.swing.JButton();
        BotonListado = new javax.swing.JButton();
        TextoDelTitulo = new javax.swing.JLabel();
        PanelDeContenido = new javax.swing.JPanel();
        PanelBaja2 = new javax.swing.JPanel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        TextFieldID5 = new javax.swing.JTextField();
        jLabel31 = new javax.swing.JLabel();
        jTextField10 = new javax.swing.JTextField();
        jSeparator9 = new javax.swing.JSeparator();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jTextField17 = new javax.swing.JTextField();
        jButton7 = new javax.swing.JButton();
        jSeparator10 = new javax.swing.JSeparator();
        PanelAlta2 = new javax.swing.JPanel();
        TituloAlta2 = new javax.swing.JLabel();
        LabelID2 = new javax.swing.JLabel();
        TextField1 = new javax.swing.JTextField();
        LabelTipo2 = new javax.swing.JLabel();
        LabelNombre2 = new javax.swing.JLabel();
        TextFieldNombre2 = new javax.swing.JTextField();
        LabelEspecie2 = new javax.swing.JLabel();
        TextFieldEspecie2 = new javax.swing.JTextField();
        LabelPeso2 = new javax.swing.JLabel();
        TextFieldPeso2 = new javax.swing.JTextField();
        LabelTipoLesion2 = new javax.swing.JLabel();
        TextFieldTipoLesion2 = new javax.swing.JTextField();
        LabelGravedadLesion3 = new javax.swing.JLabel();
        TipoAnimalComboBox2 = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        LabelFechaEntrada2 = new javax.swing.JLabel();
        LabelVeterinario2 = new javax.swing.JLabel();
        jButton8 = new javax.swing.JButton();
        TextFieldVeterinario2 = new javax.swing.JTextField();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jButton4 = new javax.swing.JButton();
        MotivoAtropello = new javax.swing.JCheckBox();
        LabelGravedadLesion1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        jLabel16.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("LIBERACION");

        jLabel18.setText("ID:");

        TextFieldID2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextFieldID2ActionPerformed(evt);
            }
        });

        jLabel19.setText("NOMBRE:");

        jLabel25.setText("FECHA:");

        jLabel26.setText("VETERINARIO:");

        jButton3.setText("GUARDAR");

        javax.swing.GroupLayout PanelLiberacionLayout = new javax.swing.GroupLayout(PanelLiberacion);
        PanelLiberacion.setLayout(PanelLiberacionLayout);
        PanelLiberacionLayout.setHorizontalGroup(
            PanelLiberacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelLiberacionLayout.createSequentialGroup()
                .addGroup(PanelLiberacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelLiberacionLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(PanelLiberacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PanelLiberacionLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(PanelLiberacionLayout.createSequentialGroup()
                                .addComponent(jLabel18)
                                .addGap(18, 18, 18)
                                .addComponent(TextFieldID2, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(92, 92, 92)
                                .addGroup(PanelLiberacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(PanelLiberacionLayout.createSequentialGroup()
                                        .addComponent(jLabel25)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(PanelLiberacionLayout.createSequentialGroup()
                                        .addComponent(jLabel26)
                                        .addGap(18, 18, 18)
                                        .addComponent(jTextField15, javax.swing.GroupLayout.DEFAULT_SIZE, 218, Short.MAX_VALUE)
                                        .addGap(6, 6, 6))))
                            .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(PanelLiberacionLayout.createSequentialGroup()
                                .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(PanelLiberacionLayout.createSequentialGroup()
                        .addGroup(PanelLiberacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PanelLiberacionLayout.createSequentialGroup()
                                .addGap(285, 285, 285)
                                .addComponent(jButton3))
                            .addGroup(PanelLiberacionLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel19)
                                .addGap(18, 18, 18)
                                .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        PanelLiberacionLayout.setVerticalGroup(
            PanelLiberacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelLiberacionLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelLiberacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(TextFieldID2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel25))
                .addGap(111, 111, 111)
                .addGroup(PanelLiberacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel26)
                    .addComponent(jTextField15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(82, 82, 82)
                .addComponent(jSeparator6, javax.swing.GroupLayout.DEFAULT_SIZE, 21, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton3)
                .addGap(43, 43, 43))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        PanelDeFondoGlobal.setBackground(new java.awt.Color(0, 51, 153));
        PanelDeFondoGlobal.setToolTipText("");
        PanelDeFondoGlobal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PanelDelMenu.setBackground(new java.awt.Color(0, 0, 0));
        PanelDelMenu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(249, 249, 249));
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("MENÚ");
        jLabel1.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jLabel1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        PanelDelMenu.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, 60, 40));

        BotonAlta.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        BotonAlta.setText("Alta");
        BotonAlta.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        BotonAlta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonAltaActionPerformed(evt);
            }
        });
        PanelDelMenu.add(BotonAlta, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 80, -1));

        BotonSalir.setBackground(new java.awt.Color(0, 0, 0));
        BotonSalir.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        BotonSalir.setForeground(new java.awt.Color(255, 255, 255));
        BotonSalir.setText("Salir");
        BotonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonSalirActionPerformed(evt);
            }
        });
        PanelDelMenu.add(BotonSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 450, 100, 30));

        BotonBaja.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        BotonBaja.setText("Baja");
        BotonBaja.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        BotonBaja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonBajaActionPerformed(evt);
            }
        });
        PanelDelMenu.add(BotonBaja, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 80, -1));

        BotonTratamiento.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        BotonTratamiento.setText("Tratamiento");
        BotonTratamiento.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        BotonTratamiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonTratamientoActionPerformed(evt);
            }
        });
        PanelDelMenu.add(BotonTratamiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, 80, -1));

        BotonLiberacion.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        BotonLiberacion.setText("Liberacion");
        BotonLiberacion.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        BotonLiberacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonLiberacionActionPerformed(evt);
            }
        });
        PanelDelMenu.add(BotonLiberacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, 80, -1));

        BotonListado.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        BotonListado.setText("Listado");
        BotonListado.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        BotonListado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonListadoActionPerformed(evt);
            }
        });
        PanelDelMenu.add(BotonListado, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, 80, -1));

        PanelDeFondoGlobal.add(PanelDelMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 140, 500));

        TextoDelTitulo.setBackground(new java.awt.Color(255, 255, 255));
        TextoDelTitulo.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 18)); // NOI18N
        TextoDelTitulo.setForeground(new java.awt.Color(255, 255, 255));
        TextoDelTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TextoDelTitulo.setText("CENTRO DE RECUPERACION DE ANIMALES SALVAJES");
        PanelDeFondoGlobal.add(TextoDelTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 0, 560, 60));

        PanelDeContenido.setLayout(new java.awt.CardLayout());

        PanelBaja2.setBackground(new java.awt.Color(0, 51, 102));
        PanelBaja2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel29.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel29.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel29.setText("DAR DE BAJA");
        PanelBaja2.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 933, 240, 30));

        jLabel30.setText("ID:");
        PanelBaja2.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 1040, -1, -1));

        TextFieldID5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextFieldID1ActionPerformed(evt);
            }
        });
        PanelBaja2.add(TextFieldID5, new org.netbeans.lib.awtextra.AbsoluteConstraints(38, 1037, 208, -1));

        jLabel31.setText("NOMBRE:");
        PanelBaja2.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 1173, -1, -1));
        PanelBaja2.add(jTextField10, new org.netbeans.lib.awtextra.AbsoluteConstraints(76, 1170, 170, -1));
        PanelBaja2.add(jSeparator9, new org.netbeans.lib.awtextra.AbsoluteConstraints(1183, 969, 50, 62));

        jLabel32.setText("FECHA:");
        PanelBaja2.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(1183, 1040, -1, -1));

        jLabel33.setText("VETERINARIO:");
        PanelBaja2.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(1183, 1173, -1, -1));
        PanelBaja2.add(jTextField17, new org.netbeans.lib.awtextra.AbsoluteConstraints(1275, 1170, 1, -1));

        jButton7.setText("GUARDAR");
        PanelBaja2.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(285, 1281, -1, -1));
        PanelBaja2.add(jSeparator10, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 1274, 50, 1));

        PanelAlta2.setBackground(new java.awt.Color(221, 229, 255));
        PanelAlta2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TituloAlta2.setBackground(new java.awt.Color(212, 217, 249));
        TituloAlta2.setFont(new java.awt.Font("Rockwell Condensed", 1, 24)); // NOI18N
        TituloAlta2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TituloAlta2.setText("DAR DE ALTA");
        TituloAlta2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        PanelAlta2.add(TituloAlta2, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, 635, 30));

        LabelID2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        LabelID2.setText("ID:");
        PanelAlta2.add(LabelID2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 26, -1));

        TextField1.setToolTipText("ID identificativo");
        TextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextFieldIDActionPerformed(evt);
            }
        });
        PanelAlta2.add(TextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 90, 86, -1));

        LabelTipo2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        LabelTipo2.setText("TIPO:");
        PanelAlta2.add(LabelTipo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, -1, -1));

        LabelNombre2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        LabelNombre2.setText("NOMBRE:");
        PanelAlta2.add(LabelNombre2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, -1, -1));

        TextFieldNombre2.setToolTipText("Nombre del Animal");
        TextFieldNombre2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextFieldNombreActionPerformed(evt);
            }
        });
        PanelAlta2.add(TextFieldNombre2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 180, 176, -1));

        LabelEspecie2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        LabelEspecie2.setText("ESPECIE:");
        PanelAlta2.add(LabelEspecie2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, -1, -1));

        TextFieldEspecie2.setToolTipText("Especie del Animal");
        PanelAlta2.add(TextFieldEspecie2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 230, 170, -1));

        LabelPeso2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        LabelPeso2.setText("PESO:");
        PanelAlta2.add(LabelPeso2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, -1, -1));

        TextFieldPeso2.setForeground(new java.awt.Color(102, 102, 102));
        TextFieldPeso2.setToolTipText("Peso en libras (lbs)");
        TextFieldPeso2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextFieldPesoActionPerformed(evt);
            }
        });
        PanelAlta2.add(TextFieldPeso2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 280, 81, -1));

        LabelTipoLesion2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        LabelTipoLesion2.setText("TIPO DE LESION:");
        PanelAlta2.add(LabelTipoLesion2, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 90, -1, 20));
        PanelAlta2.add(TextFieldTipoLesion2, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 90, 90, -1));

        LabelGravedadLesion3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        LabelGravedadLesion3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelGravedadLesion3.setText("DE LA LESION:"); // NOI18N
        PanelAlta2.add(LabelGravedadLesion3, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 140, -1, 20));

        TipoAnimalComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mamífero", "Ave", "Reptil" }));
        TipoAnimalComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TipoAnimalComboBoxActionPerformed(evt);
            }
        });
        PanelAlta2.add(TipoAnimalComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 130, -1, -1));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel12.setText("MOTIVO DE LESION:");
        PanelAlta2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 180, 149, -1));

        LabelFechaEntrada2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        LabelFechaEntrada2.setText("FECHA DE ENTRADA:");
        PanelAlta2.add(LabelFechaEntrada2, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 220, -1, -1));

        LabelVeterinario2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        LabelVeterinario2.setText("VETERINARIO:");
        PanelAlta2.add(LabelVeterinario2, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 270, -1, -1));

        jButton8.setBackground(new java.awt.Color(0, 102, 0));
        jButton8.setFont(new java.awt.Font("Arial Black", 1, 10)); // NOI18N
        jButton8.setForeground(new java.awt.Color(255, 255, 255));
        jButton8.setText("GUARDAR");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        PanelAlta2.add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 320, -1, 20));

        TextFieldVeterinario2.setToolTipText("Nombre del Veterinario asignado");
        PanelAlta2.add(TextFieldVeterinario2, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 270, 117, -1));
        PanelAlta2.add(jDateChooser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 220, 96, -1));

        jButton4.setBackground(new java.awt.Color(153, 0, 0));
        jButton4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("Restablecer información");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        PanelAlta2.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 40, 170, 20));

        MotivoAtropello.setBackground(new java.awt.Color(214, 213, 232));
        MotivoAtropello.setForeground(new java.awt.Color(0, 0, 102));
        MotivoAtropello.setText("Atropello");
        MotivoAtropello.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MotivoAtropelloActionPerformed(evt);
            }
        });
        PanelAlta2.add(MotivoAtropello, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 180, -1, 22));

        LabelGravedadLesion1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        LabelGravedadLesion1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelGravedadLesion1.setText("GRAVEDAD"); // NOI18N
        PanelAlta2.add(LabelGravedadLesion1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 120, -1, -1));

        PanelBaja2.add(PanelAlta2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, -1, 360));

        PanelDeContenido.add(PanelBaja2, "card2");

        PanelDeFondoGlobal.add(PanelDeContenido, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 60, 660, 440));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Clases/nido-logo-n (1).png"))); // NOI18N
        jLabel2.setAutoscrolls(true);
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel2.setMaximumSize(new java.awt.Dimension(50, 50));
        jLabel2.setMinimumSize(new java.awt.Dimension(50, 50));
        jLabel2.setName(""); // NOI18N
        jLabel2.setPreferredSize(new java.awt.Dimension(50, 50));
        PanelDeFondoGlobal.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 10, 60, 50));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(PanelDeFondoGlobal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelDeFondoGlobal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void BotonAltaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonAltaActionPerformed
        PanelDeContenido.removeAll();
        PanelDeContenido.add(PanelAlta);
        PanelDeContenido.repaint();
        PanelDeContenido.revalidate();
    }//GEN-LAST:event_BotonAltaActionPerformed

    private void BotonBajaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonBajaActionPerformed
        // TODO add your handling code here:
        PanelDeContenido.removeAll();
        PanelDeContenido.add(PanelBaja);
        PanelDeContenido.repaint();
        PanelDeContenido.revalidate();
    }//GEN-LAST:event_BotonBajaActionPerformed

    private void BotonTratamientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonTratamientoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BotonTratamientoActionPerformed

    private void BotonLiberacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonLiberacionActionPerformed
        // TODO add your handling code here:
        PanelDeContenido.removeAll();
        PanelDeContenido.add(PanelLiberacion);
        PanelDeContenido.repaint();
        PanelDeContenido.revalidate();
    }//GEN-LAST:event_BotonLiberacionActionPerformed

    private void BotonListadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonListadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BotonListadoActionPerformed

    private void BotonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_BotonSalirActionPerformed

    private void TextFieldID2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextFieldID2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextFieldID2ActionPerformed

    private void MotivoAtropelloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MotivoAtropelloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MotivoAtropelloActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        //Este es el botón de limpiar https://www.youtube.com/watch?v=bPZTflC3Umw
        TextField1.setText(""); 
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void TipoAnimalComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TipoAnimalComboBoxActionPerformed
        // TODO add your handling code here:
        switch (TipoAnimalComboBox.getSelectedIndex()) {
            case 0: // Mamífero
            PanelLesionAve.setVisible(false);
            break;
            case 1: // Ave
            PanelLesionAve.setVisible(true);
            break;
            case 2: // Reptil
            PanelLesionAve.setVisible(false);
            break;
        }
        PanelMotivoLesion.revalidate();
        PanelMotivoLesion.repaint();
    }//GEN-LAST:event_TipoAnimalComboBoxActionPerformed

    private void TextFieldPesoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextFieldPesoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextFieldPesoActionPerformed

    private void TextFieldNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextFieldNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextFieldNombreActionPerformed

    private void TextFieldIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextFieldIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextFieldIDActionPerformed

    private void TextFieldID1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextFieldID1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextFieldID1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interfaz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonAlta;
    private javax.swing.JButton BotonBaja;
    private javax.swing.JButton BotonLiberacion;
    private javax.swing.JButton BotonListado;
    private javax.swing.JButton BotonSalir;
    private javax.swing.JButton BotonTratamiento;
    private javax.swing.JLabel LabelEspecie;
    private javax.swing.JLabel LabelEspecie1;
    private javax.swing.JLabel LabelEspecie2;
    private javax.swing.JLabel LabelFechaEntrada;
    private javax.swing.JLabel LabelFechaEntrada1;
    private javax.swing.JLabel LabelFechaEntrada2;
    private javax.swing.JLabel LabelGravedadLesion;
    private javax.swing.JLabel LabelGravedadLesion1;
    private javax.swing.JLabel LabelGravedadLesion2;
    private javax.swing.JLabel LabelGravedadLesion3;
    private javax.swing.JLabel LabelID;
    private javax.swing.JLabel LabelID1;
    private javax.swing.JLabel LabelID2;
    private javax.swing.JLabel LabelNombre;
    private javax.swing.JLabel LabelNombre1;
    private javax.swing.JLabel LabelNombre2;
    private javax.swing.JLabel LabelPeso;
    private javax.swing.JLabel LabelPeso1;
    private javax.swing.JLabel LabelPeso2;
    private javax.swing.JLabel LabelTipo;
    private javax.swing.JLabel LabelTipo1;
    private javax.swing.JLabel LabelTipo2;
    private javax.swing.JLabel LabelTipoLesion;
    private javax.swing.JLabel LabelTipoLesion1;
    private javax.swing.JLabel LabelTipoLesion2;
    private javax.swing.JLabel LabelVeterinario;
    private javax.swing.JLabel LabelVeterinario1;
    private javax.swing.JLabel LabelVeterinario2;
    private javax.swing.JCheckBox MotivoAtropello;
    private javax.swing.JCheckBox MotivoCazaFurtiva;
    private javax.swing.JCheckBox MotivoCazaFurtiva1;
    private javax.swing.JPanel PanelAlta;
    private javax.swing.JPanel PanelAlta1;
    private javax.swing.JPanel PanelAlta2;
    private javax.swing.JPanel PanelBaja;
    private javax.swing.JPanel PanelBaja1;
    private javax.swing.JPanel PanelBaja2;
    private javax.swing.JPanel PanelDeContenido;
    private javax.swing.JPanel PanelDeFondoGlobal;
    private javax.swing.JPanel PanelDelMenu;
    private javax.swing.JPanel PanelLesionAve;
    private javax.swing.JPanel PanelLesionAve1;
    private javax.swing.JPanel PanelLiberacion;
    private javax.swing.JPanel PanelMotivoLesion;
    private javax.swing.JPanel PanelMotivoLesion1;
    private javax.swing.JTextField TextField1;
    private javax.swing.JTextField TextFieldEspecie;
    private javax.swing.JTextField TextFieldEspecie1;
    private javax.swing.JTextField TextFieldEspecie2;
    private javax.swing.JTextField TextFieldID;
    private javax.swing.JTextField TextFieldID1;
    private javax.swing.JTextField TextFieldID2;
    private javax.swing.JTextField TextFieldID3;
    private javax.swing.JTextField TextFieldID4;
    private javax.swing.JTextField TextFieldID5;
    private javax.swing.JTextField TextFieldNombre;
    private javax.swing.JTextField TextFieldNombre1;
    private javax.swing.JTextField TextFieldNombre2;
    private javax.swing.JTextField TextFieldPeso;
    private javax.swing.JTextField TextFieldPeso1;
    private javax.swing.JTextField TextFieldPeso2;
    private javax.swing.JTextField TextFieldTipoLesion;
    private javax.swing.JTextField TextFieldTipoLesion1;
    private javax.swing.JTextField TextFieldTipoLesion2;
    private javax.swing.JTextField TextFieldVeterinario;
    private javax.swing.JTextField TextFieldVeterinario1;
    private javax.swing.JTextField TextFieldVeterinario2;
    private javax.swing.JLabel TextoDelTitulo;
    private javax.swing.JComboBox<String> TipoAnimalComboBox;
    private javax.swing.JComboBox<String> TipoAnimalComboBox1;
    private javax.swing.JComboBox<String> TipoAnimalComboBox2;
    private javax.swing.JLabel TituloAlta;
    private javax.swing.JLabel TituloAlta1;
    private javax.swing.JLabel TituloAlta2;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField14;
    private javax.swing.JTextField jTextField15;
    private javax.swing.JTextField jTextField16;
    private javax.swing.JTextField jTextField17;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    // End of variables declaration//GEN-END:variables
}
