/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Clases;

import java.awt.CardLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.DefaultListModel;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JList;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author cesar
 */
public class Interfaz extends javax.swing.JFrame {
    /**
     * Creates new form Interfaz
     */
    static ArrayList<Mamífero> listaMamiferos = new ArrayList<>();
    static ArrayList<Ave> listaAves = new ArrayList<>();
    static ArrayList<Reptil> listaReptiles = new ArrayList<>();
    
    public Interfaz() {
        initComponents();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        GrupoBotonesGravedadLesion = new javax.swing.ButtonGroup();
        PanelDeFondoGlobal = new javax.swing.JPanel();
        PanelDelMenu = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        BotonAlta = new javax.swing.JButton();
        BotonSalir = new javax.swing.JButton();
        BotonBaja = new javax.swing.JButton();
        BotonLiberacion = new javax.swing.JButton();
        BotonListado = new javax.swing.JButton();
        TextoDelTitulo = new javax.swing.JLabel();
        PanelDeContenido = new javax.swing.JPanel();
        PanelBaja = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        TextFieldID1 = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jTextField14 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jSeparator4 = new javax.swing.JSeparator();
        PanelLiberacion = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        TextFieldID2 = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jTextField9 = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jTextField15 = new javax.swing.JTextField();
        BotonGuardarLiberacion = new javax.swing.JButton();
        PanelListado = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        ListadoAnimales = new javax.swing.JList<>();
        jButton1 = new javax.swing.JButton();
        PanelAlta = new javax.swing.JPanel();
        TituloAlta = new javax.swing.JLabel();
        LabelID = new javax.swing.JLabel();
        TextFieldID = new javax.swing.JTextField();
        LabelTipo = new javax.swing.JLabel();
        LabelNombre = new javax.swing.JLabel();
        TextFieldNombre = new javax.swing.JTextField();
        LabelEspecie = new javax.swing.JLabel();
        TextFieldEspecie = new javax.swing.JTextField();
        LabelPeso = new javax.swing.JLabel();
        TextFieldPeso = new javax.swing.JTextField();
        LabelTipoLesion = new javax.swing.JLabel();
        TextFieldTipoLesion = new javax.swing.JTextField();
        LabelGravedadLesion = new javax.swing.JLabel();
        TipoAnimalComboBox = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        LabelFechaEntrada = new javax.swing.JLabel();
        LabelVeterinario = new javax.swing.JLabel();
        TextFieldVeterinario = new javax.swing.JTextField();
        BotónGuardarAlta = new javax.swing.JButton();
        BotonGravedadAlta = new javax.swing.JRadioButton();
        BotonGravedadBaja = new javax.swing.JRadioButton();
        PanelMotivoLesion = new javax.swing.JPanel();
        PanelLesionAve = new javax.swing.JPanel();
        MotivoCazaFurtiva = new javax.swing.JCheckBox();
        PanelLesionMamifero = new javax.swing.JPanel();
        MotivoAtropello = new javax.swing.JCheckBox();
        PanelLesionReptil = new javax.swing.JPanel();
        MotivoInfeccion = new javax.swing.JCheckBox();
        DateChooserFechaEntrada = new com.toedter.calendar.JDateChooser();
        jLabel5 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        PanelDeFondoGlobal.setBackground(new java.awt.Color(0, 51, 51));
        PanelDeFondoGlobal.setToolTipText("");
        PanelDeFondoGlobal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PanelDelMenu.setBackground(new java.awt.Color(0, 0, 0));
        PanelDelMenu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("MENÚ");
        jLabel1.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.white, java.awt.Color.white));
        PanelDelMenu.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 100, 30));

        BotonAlta.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        BotonAlta.setText("Alta");
        BotonAlta.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        BotonAlta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonAltaActionPerformed(evt);
            }
        });
        PanelDelMenu.add(BotonAlta, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 80, 20));

        BotonSalir.setBackground(new java.awt.Color(51, 0, 0));
        BotonSalir.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        BotonSalir.setForeground(new java.awt.Color(255, 255, 255));
        BotonSalir.setText("Salir");
        BotonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonSalirActionPerformed(evt);
            }
        });
        PanelDelMenu.add(BotonSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 460, 100, -1));

        BotonBaja.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        BotonBaja.setText("Baja");
        BotonBaja.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        BotonBaja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonBajaActionPerformed(evt);
            }
        });
        PanelDelMenu.add(BotonBaja, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, 80, 20));

        BotonLiberacion.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        BotonLiberacion.setText("Liberacion");
        BotonLiberacion.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        BotonLiberacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonLiberacionActionPerformed(evt);
            }
        });
        PanelDelMenu.add(BotonLiberacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, 100, 20));

        BotonListado.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        BotonListado.setText("Listado");
        BotonListado.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        BotonListado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonListadoActionPerformed(evt);
            }
        });
        PanelDelMenu.add(BotonListado, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, 100, 20));

        PanelDeFondoGlobal.add(PanelDelMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 140, 500));

        TextoDelTitulo.setBackground(new java.awt.Color(255, 255, 255));
        TextoDelTitulo.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 18)); // NOI18N
        TextoDelTitulo.setForeground(new java.awt.Color(255, 255, 255));
        TextoDelTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TextoDelTitulo.setText("CENTRO DE RECUPERACION DE ANIMALES SALVAJES");
        PanelDeFondoGlobal.add(TextoDelTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 0, 660, 60));

        PanelDeContenido.setLayout(new java.awt.CardLayout());

        PanelBaja.setBackground(new java.awt.Color(0, 153, 153));
        PanelBaja.setForeground(new java.awt.Color(0, 102, 102));
        PanelBaja.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel14.setBackground(new java.awt.Color(0, 0, 0));
        jLabel14.setFont(new java.awt.Font("Rockwell Condensed", 1, 24)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("DAR DE BAJA");
        jLabel14.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        PanelBaja.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 670, 50));

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("ID:");
        PanelBaja.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, -1, -1));

        TextFieldID1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextFieldID1ActionPerformed(evt);
            }
        });
        PanelBaja.add(TextFieldID1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 130, 110, -1));

        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("NOMBRE:");
        PanelBaja.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, -1, -1));
        PanelBaja.add(jTextField7, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 180, 170, -1));

        jLabel23.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setText("FECHA:");
        PanelBaja.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 130, -1, -1));

        jLabel24.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setText("VETERINARIO:");
        PanelBaja.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 180, -1, -1));
        PanelBaja.add(jTextField14, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 180, 190, 20));

        jButton2.setBackground(new java.awt.Color(0, 102, 0));
        jButton2.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("GUARDAR");
        PanelBaja.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 370, -1, -1));
        PanelBaja.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 347, 50, 21));

        PanelDeContenido.add(PanelBaja, "card2");

        PanelLiberacion.setBackground(new java.awt.Color(0, 153, 153));
        PanelLiberacion.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        PanelLiberacion.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel16.setBackground(new java.awt.Color(0, 0, 0));
        jLabel16.setFont(new java.awt.Font("Rockwell Condensed", 1, 24)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("LIBERACION");
        jLabel16.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        PanelLiberacion.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 670, 50));

        jLabel18.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("ID:");
        PanelLiberacion.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, -1, -1));

        TextFieldID2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextFieldID2ActionPerformed(evt);
            }
        });
        PanelLiberacion.add(TextFieldID2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 130, 100, -1));

        jLabel19.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("NOMBRE:");
        PanelLiberacion.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, -1, -1));
        PanelLiberacion.add(jTextField9, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 180, 170, -1));

        jLabel25.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25.setText("FECHA:");
        PanelLiberacion.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 130, -1, -1));

        jLabel26.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(255, 255, 255));
        jLabel26.setText("VETERINARIO:");
        PanelLiberacion.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 180, -1, -1));
        PanelLiberacion.add(jTextField15, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 180, 216, -1));

        BotonGuardarLiberacion.setBackground(new java.awt.Color(0, 102, 0));
        BotonGuardarLiberacion.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        BotonGuardarLiberacion.setForeground(new java.awt.Color(255, 255, 255));
        BotonGuardarLiberacion.setText("GUARDAR");
        BotonGuardarLiberacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonGuardarLiberacionActionPerformed(evt);
            }
        });
        PanelLiberacion.add(BotonGuardarLiberacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 380, -1, -1));

        PanelDeContenido.add(PanelLiberacion, "card2");

        PanelListado.setBackground(new java.awt.Color(0, 153, 153));
        PanelListado.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel2.setFont(new java.awt.Font("Rockwell Condensed", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Listar Animales guardados");
        jLabel2.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.black, java.awt.Color.black));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Especies", "Mamíferos", "Aves", "Reptiles" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        ListadoAnimales.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jScrollPane1.setViewportView(ListadoAnimales);

        jButton1.setBackground(new java.awt.Color(204, 255, 255));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton1.setText("Listar");
        jButton1.setBorder(new javax.swing.border.MatteBorder(null));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelListadoLayout = new javax.swing.GroupLayout(PanelListado);
        PanelListado.setLayout(PanelListadoLayout);
        PanelListadoLayout.setHorizontalGroup(
            PanelListadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelListadoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 301, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 339, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addComponent(jScrollPane1)
            .addGroup(PanelListadoLayout.createSequentialGroup()
                .addGap(274, 274, 274)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PanelListadoLayout.setVerticalGroup(
            PanelListadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelListadoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelListadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 356, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(68, 68, 68))
        );

        PanelDeContenido.add(PanelListado, "card5");

        PanelAlta.setBackground(new java.awt.Color(0, 153, 153));
        PanelAlta.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TituloAlta.setBackground(new java.awt.Color(0, 0, 0));
        TituloAlta.setFont(new java.awt.Font("Rockwell Condensed", 1, 24)); // NOI18N
        TituloAlta.setForeground(new java.awt.Color(255, 255, 255));
        TituloAlta.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TituloAlta.setText("DAR DE ALTA");
        TituloAlta.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        PanelAlta.add(TituloAlta, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 670, 50));

        LabelID.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        LabelID.setForeground(new java.awt.Color(255, 255, 255));
        LabelID.setText("ID:");
        PanelAlta.add(LabelID, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, -1, -1));

        TextFieldID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextFieldIDActionPerformed(evt);
            }
        });
        PanelAlta.add(TextFieldID, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 90, 70, -1));

        LabelTipo.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        LabelTipo.setForeground(new java.awt.Color(255, 255, 255));
        LabelTipo.setText("TIPO:");
        PanelAlta.add(LabelTipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, -1, 20));

        LabelNombre.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        LabelNombre.setForeground(new java.awt.Color(255, 255, 255));
        LabelNombre.setText("NOMBRE:");
        PanelAlta.add(LabelNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, -1, -1));
        PanelAlta.add(TextFieldNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 200, 170, -1));

        LabelEspecie.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        LabelEspecie.setForeground(new java.awt.Color(255, 255, 255));
        LabelEspecie.setText("ESPECIE:");
        PanelAlta.add(LabelEspecie, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, -1, -1));
        PanelAlta.add(TextFieldEspecie, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 240, 170, -1));

        LabelPeso.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        LabelPeso.setForeground(new java.awt.Color(255, 255, 255));
        LabelPeso.setText("PESO:");
        PanelAlta.add(LabelPeso, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, -1, -1));
        PanelAlta.add(TextFieldPeso, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 280, 70, -1));

        LabelTipoLesion.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        LabelTipoLesion.setForeground(new java.awt.Color(255, 255, 255));
        LabelTipoLesion.setText("TIPO DE LESION:");
        PanelAlta.add(LabelTipoLesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 90, -1, 20));
        PanelAlta.add(TextFieldTipoLesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 90, 160, -1));

        LabelGravedadLesion.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        LabelGravedadLesion.setForeground(new java.awt.Color(255, 255, 255));
        LabelGravedadLesion.setText("GRAVEDAD DE LESION:");
        PanelAlta.add(LabelGravedadLesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 130, -1, -1));

        TipoAnimalComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mamífero", "Ave", "Reptil" }));
        TipoAnimalComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TipoAnimalComboBoxActionPerformed(evt);
            }
        });
        PanelAlta.add(TipoAnimalComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 130, 100, -1));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("MOTIVO DE LESION:");
        PanelAlta.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 190, -1, -1));

        LabelFechaEntrada.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        LabelFechaEntrada.setForeground(new java.awt.Color(255, 255, 255));
        LabelFechaEntrada.setText("FECHA DE ENTRADA:");
        PanelAlta.add(LabelFechaEntrada, new org.netbeans.lib.awtextra.AbsoluteConstraints(351, 232, -1, -1));

        LabelVeterinario.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        LabelVeterinario.setForeground(new java.awt.Color(255, 255, 255));
        LabelVeterinario.setText("VETERINARIO:");
        PanelAlta.add(LabelVeterinario, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 270, -1, -1));
        PanelAlta.add(TextFieldVeterinario, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 270, 160, -1));

        BotónGuardarAlta.setBackground(new java.awt.Color(0, 102, 0));
        BotónGuardarAlta.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        BotónGuardarAlta.setForeground(new java.awt.Color(255, 255, 255));
        BotónGuardarAlta.setText("GUARDAR");
        BotónGuardarAlta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotónGuardarAltaActionPerformed(evt);
            }
        });
        PanelAlta.add(BotónGuardarAlta, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 380, -1, -1));

        BotonGravedadAlta.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        BotonGravedadAlta.setForeground(new java.awt.Color(224, 250, 250));
        BotonGravedadAlta.setText("Alta");
        BotonGravedadAlta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonGravedadAltaActionPerformed(evt);
            }
        });
        PanelAlta.add(BotonGravedadAlta, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 130, -1, -1));

        BotonGravedadBaja.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        BotonGravedadBaja.setForeground(new java.awt.Color(224, 253, 253));
        BotonGravedadBaja.setText("Baja");
        BotonGravedadBaja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonGravedadBajaActionPerformed(evt);
            }
        });
        PanelAlta.add(BotonGravedadBaja, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 130, -1, -1));

        PanelMotivoLesion.setLayout(new java.awt.CardLayout());

        PanelLesionAve.setPreferredSize(new java.awt.Dimension(0, 22));

        MotivoCazaFurtiva.setText("Caza Furtiva");

        PanelLesionMamifero.setPreferredSize(new java.awt.Dimension(0, 22));

        MotivoAtropello.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        MotivoAtropello.setText("Atropello");
        MotivoAtropello.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MotivoAtropelloActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelLesionMamiferoLayout = new javax.swing.GroupLayout(PanelLesionMamifero);
        PanelLesionMamifero.setLayout(PanelLesionMamiferoLayout);
        PanelLesionMamiferoLayout.setHorizontalGroup(
            PanelLesionMamiferoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelLesionMamiferoLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(MotivoAtropello)
                .addContainerGap(41, Short.MAX_VALUE))
        );
        PanelLesionMamiferoLayout.setVerticalGroup(
            PanelLesionMamiferoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelLesionMamiferoLayout.createSequentialGroup()
                .addComponent(MotivoAtropello)
                .addGap(0, 2, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout PanelLesionAveLayout = new javax.swing.GroupLayout(PanelLesionAve);
        PanelLesionAve.setLayout(PanelLesionAveLayout);
        PanelLesionAveLayout.setHorizontalGroup(
            PanelLesionAveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelLesionAveLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(PanelLesionMamifero, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(PanelLesionAveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(PanelLesionAveLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(MotivoCazaFurtiva)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        PanelLesionAveLayout.setVerticalGroup(
            PanelLesionAveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelLesionAveLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(PanelLesionMamifero, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(PanelLesionAveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(PanelLesionAveLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(MotivoCazaFurtiva)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        PanelMotivoLesion.add(PanelLesionAve, "card3");

        PanelLesionReptil.setPreferredSize(new java.awt.Dimension(0, 22));

        MotivoInfeccion.setText("Infeccion Bacteriana");

        javax.swing.GroupLayout PanelLesionReptilLayout = new javax.swing.GroupLayout(PanelLesionReptil);
        PanelLesionReptil.setLayout(PanelLesionReptilLayout);
        PanelLesionReptilLayout.setHorizontalGroup(
            PanelLesionReptilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 160, Short.MAX_VALUE)
            .addGroup(PanelLesionReptilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(PanelLesionReptilLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(MotivoInfeccion)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        PanelLesionReptilLayout.setVerticalGroup(
            PanelLesionReptilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 22, Short.MAX_VALUE)
            .addGroup(PanelLesionReptilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(PanelLesionReptilLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(MotivoInfeccion)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        PanelMotivoLesion.add(PanelLesionReptil, "card4");

        PanelAlta.add(PanelMotivoLesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(494, 190, 160, -1));
        PanelAlta.add(DateChooserFechaEntrada, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 230, 100, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("TRATAMIENTO:");
        PanelAlta.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 310, -1, -1));

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        PanelAlta.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 310, 160, -1));

        PanelDeContenido.add(PanelAlta, "card2");

        PanelDeFondoGlobal.add(PanelDeContenido, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 60, 660, 440));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelDeFondoGlobal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelDeFondoGlobal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void BotonAltaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonAltaActionPerformed
        PanelDeContenido.removeAll();
        PanelDeContenido.add(PanelAlta);
        PanelDeContenido.repaint();
        PanelDeContenido.revalidate();
    }//GEN-LAST:event_BotonAltaActionPerformed

    private void BotonBajaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonBajaActionPerformed
        // TODO add your handling code here:
        PanelDeContenido.removeAll();
        PanelDeContenido.add(PanelBaja);
        PanelDeContenido.repaint();
        PanelDeContenido.revalidate();
    }//GEN-LAST:event_BotonBajaActionPerformed

    private void BotonLiberacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonLiberacionActionPerformed
        // TODO add your handling code here:
        PanelDeContenido.removeAll();
        PanelDeContenido.add(PanelLiberacion);
        PanelDeContenido.repaint();
        PanelDeContenido.revalidate();
    }//GEN-LAST:event_BotonLiberacionActionPerformed

    private void BotonListadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonListadoActionPerformed
        // TODO add your handling code here:
        PanelDeContenido.removeAll();
        PanelDeContenido.add(PanelListado);
        PanelDeContenido.repaint();
        PanelDeContenido.revalidate();
    }//GEN-LAST:event_BotonListadoActionPerformed

    private void BotonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_BotonSalirActionPerformed

    private void TextFieldIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextFieldIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextFieldIDActionPerformed

    private void TipoAnimalComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TipoAnimalComboBoxActionPerformed
        // TODO add your handling code here:
        switch (TipoAnimalComboBox.getSelectedIndex()) {
            case 0: // Mamífero
                PanelLesionAve.setVisible(false);
                PanelLesionMamifero.setVisible(true);
                PanelLesionReptil.setVisible(false);
                break;
            case 1: // Ave
                PanelLesionAve.setVisible(true);
                PanelLesionMamifero.setVisible(false);
                PanelLesionReptil.setVisible(false);
                break;
            case 2: // Reptil
                PanelLesionAve.setVisible(false);
                PanelLesionMamifero.setVisible(false);
                PanelLesionReptil.setVisible(true);
                break;
        }
        PanelMotivoLesion.revalidate();
        PanelMotivoLesion.repaint();
    }//GEN-LAST:event_TipoAnimalComboBoxActionPerformed

    private void TextFieldID1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextFieldID1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextFieldID1ActionPerformed

    private void BotónGuardarAltaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotónGuardarAltaActionPerformed
        // TODO add your handling code here:
        // Obtener los valores de los campos
        String id = TextFieldID.getText();
        String tipo = TipoAnimalComboBox.getSelectedItem().toString();
        String nombre = TextFieldNombre.getText();
        String especie = TextFieldEspecie.getText();
        String peso = TextFieldPeso.getText();
        String tipoLesion = TextFieldTipoLesion.getText();
        String gravedadLesion = BotonGravedadAlta.isSelected() ? "Alta" : "Baja";
        Date fechaEntrada = DateChooserFechaEntrada.getDate();
        String veterinario = TextFieldVeterinario.getText();
        boolean motivoLesionAtropello = MotivoAtropello.isSelected();
        boolean motivoLesionCazaFurtiva = MotivoCazaFurtiva.isSelected();
        boolean motivoLesionInfeccionBacteriana = MotivoInfeccion.isSelected();

// Verificar si todos los campos están llenos
        if (tipo.equals("") || nombre.equals("") || especie.equals("") || peso.equals("") || tipoLesion.equals("") || gravedadLesion.equals("") || fechaEntrada == null || veterinario.equals("")) {
            JOptionPane.showMessageDialog(null, "Por favor, rellene todos los campos para guardar un nuevo animal.", "Campos incompletos", JOptionPane.WARNING_MESSAGE);
        } else {
            Animal animal = null;
            switch (tipo) {
                case "Mamífero":
                    animal = new Mamífero(motivoLesionAtropello, id, tipo, nombre, especie, peso, tipoLesion, gravedadLesion, fechaEntrada, veterinario);
                    ((Mamífero) animal).setMotivoLesionAtropello(motivoLesionAtropello);
                    System.out.println(animal.toString());
                    break;
                case "Ave":
                    animal = new Ave(motivoLesionCazaFurtiva, id, tipo, nombre, especie, peso, tipoLesion, gravedadLesion, fechaEntrada, veterinario);
                    ((Ave) animal).setMotivoLesionCazaFurtiva(motivoLesionCazaFurtiva);
                    break;
                case "Reptil":
                    animal = new Reptil(motivoLesionInfeccionBacteriana, id, tipo, nombre, especie, peso, tipoLesion, gravedadLesion, fechaEntrada, veterinario);
                    ((Reptil) animal).setMotivoLesionInfeccionBacteriana(motivoLesionInfeccionBacteriana);
                    break;
            }
            if (animal != null) {
                // Agregar el nuevo animal al ArrayList correspondiente
                switch (tipo) {
                    case "Mamífero":
                        listaMamiferos.add((Mamífero) animal);
                        break;
                    case "Ave":
                        listaAves.add((Ave) animal);
                        break;
                    case "Reptil":
                        listaReptiles.add((Reptil) animal);
                        break;
                }
                // Mostrar mensaje de éxito
                JOptionPane.showMessageDialog(null, "Animal guardado exitosamente.", "Guardado exitoso", JOptionPane.INFORMATION_MESSAGE);
                // Limpiar los campos
                TextFieldNombre.setText("");
                TextFieldEspecie.setText("");
                TextFieldPeso.setText("");
                TextFieldTipoLesion.setText("");
                BotonGravedadAlta.setSelected(true);
                DateChooserFechaEntrada.setDate(null);
                TextFieldVeterinario.setText("");
                MotivoAtropello.setSelected(false);
                MotivoCazaFurtiva.setSelected(false);
                MotivoInfeccion.setSelected(false);
            }
        }
        // Mostrar un mensaje de éxito si todos los campos están rellenados
//        if (!tipo.isEmpty() && !nombre.isEmpty() && !especie.isEmpty() && peso > 0 && !tipoLesion.isEmpty() && !gravedadLesion.isEmpty() && fechaEntrada != null && !veterinario.isEmpty()) {
//            JOptionPane.showMessageDialog(null, "Animal guardado con éxito");
//            // Limpiar los campos
//            TextFieldNombre.setText("");
//            TextFieldEspecie.setText("");
//            TextFieldPeso.setText("");
//            TextFieldTipoLesion.setText("");
//            BotonGravedadAlta.setSelected(false);
//            BotonGravedadBaja.setSelected(false);
//            MotivoAtropello.setSelected(false);
//            MotivoCazaFurtiva.setSelected(false);
//            MotivoInfeccion.setSelected(false);
//            DateChooserFechaEntrada.setDate(null);
//            TextFieldVeterinario.setText("");
//
//        } else {
//            JOptionPane.showMessageDialog(null, "Por favor, rellene todos los campos para guardar un animal");
//        }
    }//GEN-LAST:event_BotónGuardarAltaActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void MotivoAtropelloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MotivoAtropelloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MotivoAtropelloActionPerformed

    private void BotonGravedadAltaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonGravedadAltaActionPerformed
        // TODO add your handling code here:
        GrupoBotonesGravedadLesion.add(BotonGravedadAlta);
    }//GEN-LAST:event_BotonGravedadAltaActionPerformed

    private void BotonGravedadBajaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonGravedadBajaActionPerformed
        // TODO add your handling code here:
        GrupoBotonesGravedadLesion.add(BotonGravedadBaja);
    }//GEN-LAST:event_BotonGravedadBajaActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       DefaultListModel modelo = new DefaultListModel();
       for (Mamífero o : listaMamiferos){
           modelo.addElement(o.toString());
       }
       for (Ave e : listaAves){
           modelo.addElement(e.toString());
       }
       for (Reptil l : listaReptiles){
           modelo.addElement(l.toString());
       }
       
       ListadoAnimales.setModel(modelo);
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void BotonGuardarLiberacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonGuardarLiberacionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BotonGuardarLiberacionActionPerformed

    private void TextFieldID2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextFieldID2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextFieldID2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interfaz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonAlta;
    private javax.swing.JButton BotonBaja;
    private javax.swing.JRadioButton BotonGravedadAlta;
    private javax.swing.JRadioButton BotonGravedadBaja;
    private javax.swing.JButton BotonGuardarLiberacion;
    private javax.swing.JButton BotonLiberacion;
    private javax.swing.JButton BotonListado;
    private javax.swing.JButton BotonSalir;
    private javax.swing.JButton BotónGuardarAlta;
    private com.toedter.calendar.JDateChooser DateChooserFechaEntrada;
    private javax.swing.ButtonGroup GrupoBotonesGravedadLesion;
    private javax.swing.JLabel LabelEspecie;
    private javax.swing.JLabel LabelFechaEntrada;
    private javax.swing.JLabel LabelGravedadLesion;
    private javax.swing.JLabel LabelID;
    private javax.swing.JLabel LabelNombre;
    private javax.swing.JLabel LabelPeso;
    private javax.swing.JLabel LabelTipo;
    private javax.swing.JLabel LabelTipoLesion;
    private javax.swing.JLabel LabelVeterinario;
    private javax.swing.JList<String> ListadoAnimales;
    private javax.swing.JCheckBox MotivoAtropello;
    private javax.swing.JCheckBox MotivoCazaFurtiva;
    private javax.swing.JCheckBox MotivoInfeccion;
    private javax.swing.JPanel PanelAlta;
    private javax.swing.JPanel PanelBaja;
    private javax.swing.JPanel PanelDeContenido;
    private javax.swing.JPanel PanelDeFondoGlobal;
    private javax.swing.JPanel PanelDelMenu;
    private javax.swing.JPanel PanelLesionAve;
    private javax.swing.JPanel PanelLesionMamifero;
    private javax.swing.JPanel PanelLesionReptil;
    private javax.swing.JPanel PanelLiberacion;
    private javax.swing.JPanel PanelListado;
    private javax.swing.JPanel PanelMotivoLesion;
    private javax.swing.JTextField TextFieldEspecie;
    private javax.swing.JTextField TextFieldID;
    private javax.swing.JTextField TextFieldID1;
    private javax.swing.JTextField TextFieldID2;
    private javax.swing.JTextField TextFieldNombre;
    private javax.swing.JTextField TextFieldPeso;
    private javax.swing.JTextField TextFieldTipoLesion;
    private javax.swing.JTextField TextFieldVeterinario;
    private javax.swing.JLabel TextoDelTitulo;
    private javax.swing.JComboBox<String> TipoAnimalComboBox;
    private javax.swing.JLabel TituloAlta;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField14;
    private javax.swing.JTextField jTextField15;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField9;
    // End of variables declaration//GEN-END:variables
}
