/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Clases;

import java.awt.CardLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.DefaultListModel;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JList;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author cesar
 */
public class Interfaz extends javax.swing.JFrame {
    /**
     * Creates new form Interfaz
     */
    static ArrayList<Mamífero> listaMamiferos = new ArrayList<>();
    static ArrayList<Ave> listaAves = new ArrayList<>();
    static ArrayList<Reptil> listaReptiles = new ArrayList<>();
    
    public Interfaz() {
        initComponents();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        GrupoBotonesGravedadLesion = new javax.swing.ButtonGroup();
        PanelDeFondoGlobal = new javax.swing.JPanel();
        PanelDelMenu = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        BotonAlta = new javax.swing.JButton();
        BotonSalir = new javax.swing.JButton();
        BotonBaja = new javax.swing.JButton();
        BotonTratamiento = new javax.swing.JButton();
        BotonLiberacion = new javax.swing.JButton();
        BotonListado = new javax.swing.JButton();
        TextoDelTitulo = new javax.swing.JLabel();
        PanelDeContenido = new javax.swing.JPanel();
        PanelAlta = new javax.swing.JPanel();
        TituloAlta = new javax.swing.JLabel();
        LabelID = new javax.swing.JLabel();
        TextFieldID = new javax.swing.JTextField();
        LabelTipo = new javax.swing.JLabel();
        LabelNombre = new javax.swing.JLabel();
        TextFieldNombre = new javax.swing.JTextField();
        LabelEspecie = new javax.swing.JLabel();
        TextFieldEspecie = new javax.swing.JTextField();
        LabelPeso = new javax.swing.JLabel();
        TextFieldPeso = new javax.swing.JTextField();
        LabelTipoLesion = new javax.swing.JLabel();
        TextFieldTipoLesion = new javax.swing.JTextField();
        LabelGravedadLesion = new javax.swing.JLabel();
        TipoAnimalComboBox = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        LabelFechaEntrada = new javax.swing.JLabel();
        LabelVeterinario = new javax.swing.JLabel();
        TextFieldVeterinario = new javax.swing.JTextField();
        BotónGuardarAlta = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        BotonGravedadAlta = new javax.swing.JRadioButton();
        BotonGravedadBaja = new javax.swing.JRadioButton();
        PanelMotivoLesion = new javax.swing.JPanel();
        PanelLesionMamifero = new javax.swing.JPanel();
        MotivoAtropello = new javax.swing.JCheckBox();
        PanelLesionAve = new javax.swing.JPanel();
        MotivoCazaFurtiva = new javax.swing.JCheckBox();
        PanelLesionReptil = new javax.swing.JPanel();
        MotivoInfeccion = new javax.swing.JCheckBox();
        DateChooserFechaEntrada = new com.toedter.calendar.JDateChooser();
        PanelBaja = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        TextFieldID1 = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jTextField14 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jSeparator4 = new javax.swing.JSeparator();
        PanelLiberacion = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        TextFieldID2 = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jTextField9 = new javax.swing.JTextField();
        jSeparator5 = new javax.swing.JSeparator();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jTextField15 = new javax.swing.JTextField();
        BotonGuardarLiberacion = new javax.swing.JButton();
        jSeparator6 = new javax.swing.JSeparator();
        PanelListado = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        ListadoAnimales = new javax.swing.JList<>();
        jButton1 = new javax.swing.JButton();
        PanelTratamiento = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        PanelDeFondoGlobal.setBackground(new java.awt.Color(102, 153, 255));
        PanelDeFondoGlobal.setToolTipText("");
        PanelDeFondoGlobal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PanelDelMenu.setBackground(new java.awt.Color(102, 153, 0));
        PanelDelMenu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("MENÚ");
        PanelDelMenu.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, 118, 40));

        BotonAlta.setText("Alta");
        BotonAlta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonAltaActionPerformed(evt);
            }
        });
        PanelDelMenu.add(BotonAlta, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 140, -1));

        BotonSalir.setText("Salir");
        BotonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonSalirActionPerformed(evt);
            }
        });
        PanelDelMenu.add(BotonSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 460, 140, -1));

        BotonBaja.setText("Baja");
        BotonBaja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonBajaActionPerformed(evt);
            }
        });
        PanelDelMenu.add(BotonBaja, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 140, -1));

        BotonTratamiento.setText("Tratamiento");
        BotonTratamiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonTratamientoActionPerformed(evt);
            }
        });
        PanelDelMenu.add(BotonTratamiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 140, -1));

        BotonLiberacion.setText("Liberacion");
        BotonLiberacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonLiberacionActionPerformed(evt);
            }
        });
        PanelDelMenu.add(BotonLiberacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 250, 140, -1));

        BotonListado.setText("Listado");
        BotonListado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonListadoActionPerformed(evt);
            }
        });
        PanelDelMenu.add(BotonListado, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 300, 140, -1));

        PanelDeFondoGlobal.add(PanelDelMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 140, 500));

        TextoDelTitulo.setBackground(new java.awt.Color(255, 255, 255));
        TextoDelTitulo.setFont(new java.awt.Font("Jokerman", 0, 18)); // NOI18N
        TextoDelTitulo.setForeground(new java.awt.Color(255, 255, 255));
        TextoDelTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TextoDelTitulo.setText("CENTRO DE RECUPERACION DE ANIMALES SALVAJES");
        PanelDeFondoGlobal.add(TextoDelTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 0, 660, 60));

        PanelDeContenido.setLayout(new java.awt.CardLayout());

        TituloAlta.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        TituloAlta.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TituloAlta.setText("DAR DE ALTA");

        LabelID.setText("ID:");

        TextFieldID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextFieldIDActionPerformed(evt);
            }
        });

        LabelTipo.setText("TIPO:");

        LabelNombre.setText("NOMBRE:");

        LabelEspecie.setText("ESPECIE:");

        LabelPeso.setText("PESO:");

        LabelTipoLesion.setText("TIPO DE LESION:");

        LabelGravedadLesion.setText("GRAVEDAD DE LESION:");

        TipoAnimalComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mamífero", "Ave", "Reptil" }));
        TipoAnimalComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TipoAnimalComboBoxActionPerformed(evt);
            }
        });

        jLabel10.setText("MOTIVO DE LESION:");

        LabelFechaEntrada.setText("FECHA DE ENTRADA:");

        LabelVeterinario.setText("VETERINARIO:");

        BotónGuardarAlta.setText("GUARDAR");
        BotónGuardarAlta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotónGuardarAltaActionPerformed(evt);
            }
        });

        BotonGravedadAlta.setText("Alta");
        BotonGravedadAlta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonGravedadAltaActionPerformed(evt);
            }
        });

        BotonGravedadBaja.setText("Baja");
        BotonGravedadBaja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonGravedadBajaActionPerformed(evt);
            }
        });

        PanelMotivoLesion.setLayout(new java.awt.CardLayout());

        PanelLesionMamifero.setPreferredSize(new java.awt.Dimension(0, 22));

        MotivoAtropello.setText("Atropello");
        MotivoAtropello.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MotivoAtropelloActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelLesionMamiferoLayout = new javax.swing.GroupLayout(PanelLesionMamifero);
        PanelLesionMamifero.setLayout(PanelLesionMamiferoLayout);
        PanelLesionMamiferoLayout.setHorizontalGroup(
            PanelLesionMamiferoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 186, Short.MAX_VALUE)
            .addGroup(PanelLesionMamiferoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(PanelLesionMamiferoLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(MotivoAtropello)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        PanelLesionMamiferoLayout.setVerticalGroup(
            PanelLesionMamiferoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 22, Short.MAX_VALUE)
            .addGroup(PanelLesionMamiferoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(PanelLesionMamiferoLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(MotivoAtropello)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        PanelMotivoLesion.add(PanelLesionMamifero, "card2");

        PanelLesionAve.setPreferredSize(new java.awt.Dimension(0, 22));

        MotivoCazaFurtiva.setText("Caza Furtiva");

        javax.swing.GroupLayout PanelLesionAveLayout = new javax.swing.GroupLayout(PanelLesionAve);
        PanelLesionAve.setLayout(PanelLesionAveLayout);
        PanelLesionAveLayout.setHorizontalGroup(
            PanelLesionAveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 186, Short.MAX_VALUE)
            .addGroup(PanelLesionAveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(PanelLesionAveLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(MotivoCazaFurtiva)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        PanelLesionAveLayout.setVerticalGroup(
            PanelLesionAveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 22, Short.MAX_VALUE)
            .addGroup(PanelLesionAveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(PanelLesionAveLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(MotivoCazaFurtiva)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        PanelMotivoLesion.add(PanelLesionAve, "card3");

        PanelLesionReptil.setPreferredSize(new java.awt.Dimension(0, 22));

        MotivoInfeccion.setText("Infeccion Bacteriana");

        javax.swing.GroupLayout PanelLesionReptilLayout = new javax.swing.GroupLayout(PanelLesionReptil);
        PanelLesionReptil.setLayout(PanelLesionReptilLayout);
        PanelLesionReptilLayout.setHorizontalGroup(
            PanelLesionReptilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 186, Short.MAX_VALUE)
            .addGroup(PanelLesionReptilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(PanelLesionReptilLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(MotivoInfeccion)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        PanelLesionReptilLayout.setVerticalGroup(
            PanelLesionReptilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 22, Short.MAX_VALUE)
            .addGroup(PanelLesionReptilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(PanelLesionReptilLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(MotivoInfeccion)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        PanelMotivoLesion.add(PanelLesionReptil, "card4");

        javax.swing.GroupLayout PanelAltaLayout = new javax.swing.GroupLayout(PanelAlta);
        PanelAlta.setLayout(PanelAltaLayout);
        PanelAltaLayout.setHorizontalGroup(
            PanelAltaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelAltaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelAltaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelAltaLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PanelAltaLayout.createSequentialGroup()
                        .addGroup(PanelAltaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(PanelAltaLayout.createSequentialGroup()
                                .addComponent(LabelID)
                                .addGap(18, 18, 18)
                                .addComponent(TextFieldID))
                            .addGroup(PanelAltaLayout.createSequentialGroup()
                                .addComponent(LabelTipo)
                                .addGap(18, 18, 18)
                                .addComponent(TipoAnimalComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(PanelAltaLayout.createSequentialGroup()
                                .addComponent(LabelNombre)
                                .addGap(18, 18, 18)
                                .addComponent(TextFieldNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(PanelAltaLayout.createSequentialGroup()
                                .addComponent(LabelEspecie)
                                .addGap(18, 18, 18)
                                .addComponent(TextFieldEspecie))
                            .addGroup(PanelAltaLayout.createSequentialGroup()
                                .addComponent(LabelPeso)
                                .addGap(18, 18, 18)
                                .addComponent(TextFieldPeso)))
                        .addGap(98, 98, 98)
                        .addGroup(PanelAltaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PanelAltaLayout.createSequentialGroup()
                                .addComponent(LabelTipoLesion)
                                .addGap(18, 18, 18)
                                .addComponent(TextFieldTipoLesion))
                            .addGroup(PanelAltaLayout.createSequentialGroup()
                                .addComponent(LabelVeterinario)
                                .addGap(18, 18, 18)
                                .addComponent(TextFieldVeterinario))
                            .addGroup(PanelAltaLayout.createSequentialGroup()
                                .addComponent(LabelGravedadLesion)
                                .addGap(39, 39, 39)
                                .addComponent(BotonGravedadAlta)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                                .addComponent(BotonGravedadBaja)
                                .addGap(22, 22, 22))
                            .addGroup(PanelAltaLayout.createSequentialGroup()
                                .addGroup(PanelAltaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel10)
                                    .addComponent(LabelFechaEntrada))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(PanelAltaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(PanelMotivoLesion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(DateChooserFechaEntrada, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                    .addComponent(TituloAlta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(PanelAltaLayout.createSequentialGroup()
                        .addGroup(PanelAltaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PanelAltaLayout.createSequentialGroup()
                                .addGap(279, 279, 279)
                                .addComponent(BotónGuardarAlta))
                            .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        PanelAltaLayout.setVerticalGroup(
            PanelAltaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelAltaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(TituloAlta, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelAltaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(PanelAltaLayout.createSequentialGroup()
                        .addGroup(PanelAltaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LabelID)
                            .addComponent(TextFieldID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LabelTipoLesion)
                            .addComponent(TextFieldTipoLesion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(PanelAltaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LabelTipo)
                            .addComponent(LabelGravedadLesion)
                            .addComponent(TipoAnimalComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BotonGravedadAlta)
                            .addComponent(BotonGravedadBaja))
                        .addGap(18, 18, 18)
                        .addGroup(PanelAltaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(PanelAltaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(LabelNombre)
                                .addComponent(TextFieldNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel10))
                            .addComponent(PanelMotivoLesion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(PanelAltaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LabelEspecie)
                            .addComponent(TextFieldEspecie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LabelFechaEntrada)))
                    .addComponent(DateChooserFechaEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PanelAltaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelPeso)
                    .addComponent(TextFieldPeso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabelVeterinario)
                    .addComponent(TextFieldVeterinario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(61, 61, 61)
                .addComponent(jSeparator2, javax.swing.GroupLayout.DEFAULT_SIZE, 15, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BotónGuardarAlta)
                .addGap(43, 43, 43))
        );

        PanelDeContenido.add(PanelAlta, "card2");

        jLabel14.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("DAR DE BAJA");

        jLabel15.setText("ID:");

        TextFieldID1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextFieldID1ActionPerformed(evt);
            }
        });

        jLabel17.setText("NOMBRE:");

        jLabel23.setText("FECHA:");

        jLabel24.setText("VETERINARIO:");

        jButton2.setText("GUARDAR");

        javax.swing.GroupLayout PanelBajaLayout = new javax.swing.GroupLayout(PanelBaja);
        PanelBaja.setLayout(PanelBajaLayout);
        PanelBajaLayout.setHorizontalGroup(
            PanelBajaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelBajaLayout.createSequentialGroup()
                .addGroup(PanelBajaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelBajaLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(PanelBajaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PanelBajaLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(PanelBajaLayout.createSequentialGroup()
                                .addComponent(jLabel15)
                                .addGap(18, 18, 18)
                                .addComponent(TextFieldID1, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(92, 92, 92)
                                .addGroup(PanelBajaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(PanelBajaLayout.createSequentialGroup()
                                        .addComponent(jLabel23)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(PanelBajaLayout.createSequentialGroup()
                                        .addComponent(jLabel24)
                                        .addGap(18, 18, 18)
                                        .addComponent(jTextField14, javax.swing.GroupLayout.DEFAULT_SIZE, 218, Short.MAX_VALUE)
                                        .addGap(6, 6, 6))))
                            .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(PanelBajaLayout.createSequentialGroup()
                                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(PanelBajaLayout.createSequentialGroup()
                        .addGroup(PanelBajaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PanelBajaLayout.createSequentialGroup()
                                .addGap(285, 285, 285)
                                .addComponent(jButton2))
                            .addGroup(PanelBajaLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel17)
                                .addGap(18, 18, 18)
                                .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        PanelBajaLayout.setVerticalGroup(
            PanelBajaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelBajaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelBajaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(TextFieldID1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel23))
                .addGap(111, 111, 111)
                .addGroup(PanelBajaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel24)
                    .addComponent(jTextField14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(82, 82, 82)
                .addComponent(jSeparator4, javax.swing.GroupLayout.DEFAULT_SIZE, 21, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2)
                .addGap(43, 43, 43))
        );

        PanelDeContenido.add(PanelBaja, "card2");

        jLabel16.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("LIBERACION");

        jLabel18.setText("ID:");

        TextFieldID2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextFieldID2ActionPerformed(evt);
            }
        });

        jLabel19.setText("NOMBRE:");

        jLabel25.setText("FECHA:");

        jLabel26.setText("VETERINARIO:");

        BotonGuardarLiberacion.setText("GUARDAR");
        BotonGuardarLiberacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonGuardarLiberacionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelLiberacionLayout = new javax.swing.GroupLayout(PanelLiberacion);
        PanelLiberacion.setLayout(PanelLiberacionLayout);
        PanelLiberacionLayout.setHorizontalGroup(
            PanelLiberacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelLiberacionLayout.createSequentialGroup()
                .addGroup(PanelLiberacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelLiberacionLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(PanelLiberacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PanelLiberacionLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(PanelLiberacionLayout.createSequentialGroup()
                                .addComponent(jLabel18)
                                .addGap(18, 18, 18)
                                .addComponent(TextFieldID2, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(92, 92, 92)
                                .addGroup(PanelLiberacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(PanelLiberacionLayout.createSequentialGroup()
                                        .addComponent(jLabel25)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(PanelLiberacionLayout.createSequentialGroup()
                                        .addComponent(jLabel26)
                                        .addGap(18, 18, 18)
                                        .addComponent(jTextField15, javax.swing.GroupLayout.DEFAULT_SIZE, 218, Short.MAX_VALUE)
                                        .addGap(6, 6, 6))))
                            .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(PanelLiberacionLayout.createSequentialGroup()
                                .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(PanelLiberacionLayout.createSequentialGroup()
                        .addGroup(PanelLiberacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PanelLiberacionLayout.createSequentialGroup()
                                .addGap(285, 285, 285)
                                .addComponent(BotonGuardarLiberacion))
                            .addGroup(PanelLiberacionLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel19)
                                .addGap(18, 18, 18)
                                .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        PanelLiberacionLayout.setVerticalGroup(
            PanelLiberacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelLiberacionLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelLiberacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(TextFieldID2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel25))
                .addGap(111, 111, 111)
                .addGroup(PanelLiberacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel26)
                    .addComponent(jTextField15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(82, 82, 82)
                .addComponent(jSeparator6, javax.swing.GroupLayout.DEFAULT_SIZE, 21, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BotonGuardarLiberacion)
                .addGap(43, 43, 43))
        );

        PanelDeContenido.add(PanelLiberacion, "card2");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Listar Animales guardados");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Todos", "Mamíferos", "Aves", "Reptiles" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jScrollPane1.setViewportView(ListadoAnimales);

        jButton1.setText("listar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelListadoLayout = new javax.swing.GroupLayout(PanelListado);
        PanelListado.setLayout(PanelListadoLayout);
        PanelListadoLayout.setHorizontalGroup(
            PanelListadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelListadoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 291, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 339, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addComponent(jScrollPane1)
            .addGroup(PanelListadoLayout.createSequentialGroup()
                .addGap(274, 274, 274)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PanelListadoLayout.setVerticalGroup(
            PanelListadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelListadoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelListadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jComboBox1)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addGap(28, 28, 28)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 356, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(68, 68, 68))
        );

        PanelDeContenido.add(PanelListado, "card5");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("TRATAMIENTO");

        jLabel4.setText("Tratamiento para el Animal");

        javax.swing.GroupLayout PanelTratamientoLayout = new javax.swing.GroupLayout(PanelTratamiento);
        PanelTratamiento.setLayout(PanelTratamientoLayout);
        PanelTratamientoLayout.setHorizontalGroup(
            PanelTratamientoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelTratamientoLayout.createSequentialGroup()
                .addGap(248, 248, 248)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(292, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelTratamientoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(185, 185, 185))
        );
        PanelTratamientoLayout.setVerticalGroup(
            PanelTratamientoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelTratamientoLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(65, 65, 65)
                .addComponent(jLabel4)
                .addContainerGap(312, Short.MAX_VALUE))
        );

        PanelDeContenido.add(PanelTratamiento, "card6");

        PanelDeFondoGlobal.add(PanelDeContenido, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 60, 660, 440));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelDeFondoGlobal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelDeFondoGlobal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void BotonAltaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonAltaActionPerformed
        PanelDeContenido.removeAll();
        PanelDeContenido.add(PanelAlta);
        PanelDeContenido.repaint();
        PanelDeContenido.revalidate();
    }//GEN-LAST:event_BotonAltaActionPerformed

    private void BotonBajaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonBajaActionPerformed
        // TODO add your handling code here:
        PanelDeContenido.removeAll();
        PanelDeContenido.add(PanelBaja);
        PanelDeContenido.repaint();
        PanelDeContenido.revalidate();
    }//GEN-LAST:event_BotonBajaActionPerformed

    private void BotonTratamientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonTratamientoActionPerformed
        // TODO add your handling code here:
        PanelDeContenido.removeAll();
        PanelDeContenido.add(PanelTratamiento);
        PanelDeContenido.repaint();
        PanelDeContenido.revalidate();
    }//GEN-LAST:event_BotonTratamientoActionPerformed

    private void BotonLiberacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonLiberacionActionPerformed
        // TODO add your handling code here:
        PanelDeContenido.removeAll();
        PanelDeContenido.add(PanelLiberacion);
        PanelDeContenido.repaint();
        PanelDeContenido.revalidate();
    }//GEN-LAST:event_BotonLiberacionActionPerformed

    private void BotonListadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonListadoActionPerformed
        // TODO add your handling code here:
        PanelDeContenido.removeAll();
        PanelDeContenido.add(PanelListado);
        PanelDeContenido.repaint();
        PanelDeContenido.revalidate();
    }//GEN-LAST:event_BotonListadoActionPerformed

    private void BotonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_BotonSalirActionPerformed

    private void TextFieldIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextFieldIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextFieldIDActionPerformed

    private void TipoAnimalComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TipoAnimalComboBoxActionPerformed
        // TODO add your handling code here:
        switch (TipoAnimalComboBox.getSelectedIndex()) {
            case 0: // Mamífero
                PanelLesionAve.setVisible(false);
                PanelLesionMamifero.setVisible(true);
                PanelLesionReptil.setVisible(false);
                break;
            case 1: // Ave
                PanelLesionAve.setVisible(true);
                PanelLesionMamifero.setVisible(false);
                PanelLesionReptil.setVisible(false);
                break;
            case 2: // Reptil
                PanelLesionAve.setVisible(false);
                PanelLesionMamifero.setVisible(false);
                PanelLesionReptil.setVisible(true);
                break;
        }
        PanelMotivoLesion.revalidate();
        PanelMotivoLesion.repaint();
    }//GEN-LAST:event_TipoAnimalComboBoxActionPerformed

    private void TextFieldID1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextFieldID1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextFieldID1ActionPerformed

    private void TextFieldID2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextFieldID2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextFieldID2ActionPerformed

    private void BotónGuardarAltaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotónGuardarAltaActionPerformed
        // TODO add your handling code here:
        // Obtener los valores de los campos
        String id = TextFieldID.getText();
        String tipo = TipoAnimalComboBox.getSelectedItem().toString();
        String nombre = TextFieldNombre.getText();
        String especie = TextFieldEspecie.getText();
        String peso = TextFieldPeso.getText();
        String tipoLesion = TextFieldTipoLesion.getText();
        String gravedadLesion = BotonGravedadAlta.isSelected() ? "Alta" : "Baja";
        Date fechaEntrada = DateChooserFechaEntrada.getDate();
        String veterinario = TextFieldVeterinario.getText();
        boolean motivoLesionAtropello = MotivoAtropello.isSelected();
        boolean motivoLesionCazaFurtiva = MotivoCazaFurtiva.isSelected();
        boolean motivoLesionInfeccionBacteriana = MotivoInfeccion.isSelected();

// Verificar si todos los campos están llenos
        if (tipo.equals("") || nombre.equals("") || especie.equals("") || peso.equals("") || tipoLesion.equals("") || gravedadLesion.equals("") || fechaEntrada == null || veterinario.equals("")) {
            JOptionPane.showMessageDialog(null, "Por favor, rellene todos los campos para guardar un nuevo animal.", "Campos incompletos", JOptionPane.WARNING_MESSAGE);
        } else {
            Animal animal = null;
            switch (tipo) {
                case "Mamífero":
                    animal = new Mamífero(motivoLesionAtropello, id, tipo, nombre, especie, peso, tipoLesion, gravedadLesion, fechaEntrada, veterinario);
                    ((Mamífero) animal).setMotivoLesionAtropello(motivoLesionAtropello);
                    System.out.println(animal.toString());
                    break;
                case "Ave":
                    animal = new Ave(motivoLesionCazaFurtiva, id, tipo, nombre, especie, peso, tipoLesion, gravedadLesion, fechaEntrada, veterinario);
                    ((Ave) animal).setMotivoLesionCazaFurtiva(motivoLesionCazaFurtiva);
                    break;
                case "Reptil":
                    animal = new Reptil(motivoLesionInfeccionBacteriana, id, tipo, nombre, especie, peso, tipoLesion, gravedadLesion, fechaEntrada, veterinario);
                    ((Reptil) animal).setMotivoLesionInfeccionBacteriana(motivoLesionInfeccionBacteriana);
                    break;
            }
            if (animal != null) {
                // Agregar el nuevo animal al ArrayList correspondiente
                switch (tipo) {
                    case "Mamífero":
                        listaMamiferos.add((Mamífero) animal);
                        break;
                    case "Ave":
                        listaAves.add((Ave) animal);
                        break;
                    case "Reptil":
                        listaReptiles.add((Reptil) animal);
                        break;
                }
                // Mostrar mensaje de éxito
                JOptionPane.showMessageDialog(null, "Animal guardado exitosamente.", "Guardado exitoso", JOptionPane.INFORMATION_MESSAGE);
                // Limpiar los campos
                TextFieldNombre.setText("");
                TextFieldEspecie.setText("");
                TextFieldPeso.setText("");
                TextFieldTipoLesion.setText("");
                BotonGravedadAlta.setSelected(true);
                DateChooserFechaEntrada.setDate(null);
                TextFieldVeterinario.setText("");
                MotivoAtropello.setSelected(false);
                MotivoCazaFurtiva.setSelected(false);
                MotivoInfeccion.setSelected(false);
            }
        }
        // Mostrar un mensaje de éxito si todos los campos están rellenados
//        if (!tipo.isEmpty() && !nombre.isEmpty() && !especie.isEmpty() && peso > 0 && !tipoLesion.isEmpty() && !gravedadLesion.isEmpty() && fechaEntrada != null && !veterinario.isEmpty()) {
//            JOptionPane.showMessageDialog(null, "Animal guardado con éxito");
//            // Limpiar los campos
//            TextFieldNombre.setText("");
//            TextFieldEspecie.setText("");
//            TextFieldPeso.setText("");
//            TextFieldTipoLesion.setText("");
//            BotonGravedadAlta.setSelected(false);
//            BotonGravedadBaja.setSelected(false);
//            MotivoAtropello.setSelected(false);
//            MotivoCazaFurtiva.setSelected(false);
//            MotivoInfeccion.setSelected(false);
//            DateChooserFechaEntrada.setDate(null);
//            TextFieldVeterinario.setText("");
//
//        } else {
//            JOptionPane.showMessageDialog(null, "Por favor, rellene todos los campos para guardar un animal");
//        }
    }//GEN-LAST:event_BotónGuardarAltaActionPerformed

    private void BotonGuardarLiberacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonGuardarLiberacionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BotonGuardarLiberacionActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void MotivoAtropelloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MotivoAtropelloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MotivoAtropelloActionPerformed

    private void BotonGravedadAltaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonGravedadAltaActionPerformed
        // TODO add your handling code here:
        GrupoBotonesGravedadLesion.add(BotonGravedadAlta);
    }//GEN-LAST:event_BotonGravedadAltaActionPerformed

    private void BotonGravedadBajaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonGravedadBajaActionPerformed
        // TODO add your handling code here:
        GrupoBotonesGravedadLesion.add(BotonGravedadBaja);
    }//GEN-LAST:event_BotonGravedadBajaActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       DefaultListModel modelo = new DefaultListModel();
       for (Mamífero o : listaMamiferos){
           modelo.addElement(o.toString());
       }
       for (Ave e : listaAves){
           modelo.addElement(e.toString());
       }
       for (Reptil l : listaReptiles){
           modelo.addElement(l.toString());
       }
       
       ListadoAnimales.setModel(modelo);
        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interfaz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonAlta;
    private javax.swing.JButton BotonBaja;
    private javax.swing.JRadioButton BotonGravedadAlta;
    private javax.swing.JRadioButton BotonGravedadBaja;
    private javax.swing.JButton BotonGuardarLiberacion;
    private javax.swing.JButton BotonLiberacion;
    private javax.swing.JButton BotonListado;
    private javax.swing.JButton BotonSalir;
    private javax.swing.JButton BotonTratamiento;
    private javax.swing.JButton BotónGuardarAlta;
    private com.toedter.calendar.JDateChooser DateChooserFechaEntrada;
    private javax.swing.ButtonGroup GrupoBotonesGravedadLesion;
    private javax.swing.JLabel LabelEspecie;
    private javax.swing.JLabel LabelFechaEntrada;
    private javax.swing.JLabel LabelGravedadLesion;
    private javax.swing.JLabel LabelID;
    private javax.swing.JLabel LabelNombre;
    private javax.swing.JLabel LabelPeso;
    private javax.swing.JLabel LabelTipo;
    private javax.swing.JLabel LabelTipoLesion;
    private javax.swing.JLabel LabelVeterinario;
    private javax.swing.JList<String> ListadoAnimales;
    private javax.swing.JCheckBox MotivoAtropello;
    private javax.swing.JCheckBox MotivoCazaFurtiva;
    private javax.swing.JCheckBox MotivoInfeccion;
    private javax.swing.JPanel PanelAlta;
    private javax.swing.JPanel PanelBaja;
    private javax.swing.JPanel PanelDeContenido;
    private javax.swing.JPanel PanelDeFondoGlobal;
    private javax.swing.JPanel PanelDelMenu;
    private javax.swing.JPanel PanelLesionAve;
    private javax.swing.JPanel PanelLesionMamifero;
    private javax.swing.JPanel PanelLesionReptil;
    private javax.swing.JPanel PanelLiberacion;
    private javax.swing.JPanel PanelListado;
    private javax.swing.JPanel PanelMotivoLesion;
    private javax.swing.JPanel PanelTratamiento;
    private javax.swing.JTextField TextFieldEspecie;
    private javax.swing.JTextField TextFieldID;
    private javax.swing.JTextField TextFieldID1;
    private javax.swing.JTextField TextFieldID2;
    private javax.swing.JTextField TextFieldNombre;
    private javax.swing.JTextField TextFieldPeso;
    private javax.swing.JTextField TextFieldTipoLesion;
    private javax.swing.JTextField TextFieldVeterinario;
    private javax.swing.JLabel TextoDelTitulo;
    private javax.swing.JComboBox<String> TipoAnimalComboBox;
    private javax.swing.JLabel TituloAlta;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JTextField jTextField14;
    private javax.swing.JTextField jTextField15;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField9;
    // End of variables declaration//GEN-END:variables
}
