/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Clases;

import java.awt.CardLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.DefaultListModel;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JList;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author cesar
 */
public class Interfaz extends javax.swing.JFrame {

    /**
     * Creates new form Interfaz
     */
    static ArrayList<Mamífero> listaMamíferos = new ArrayList<>();
    static ArrayList<Ave> listaAves = new ArrayList<>();
    static ArrayList<Reptil> listaReptiles = new ArrayList<>();
    static ArrayList<Animal> listaBajas = new ArrayList<>();
    static ArrayList<Animal> listaLiberados = new ArrayList<>();

    
    public Interfaz() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        GrupoBotonesGravedadLesion = new javax.swing.ButtonGroup();
        PanelDeFondoGlobal = new javax.swing.JPanel();
        PanelDelMenu = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        BotonAlta = new javax.swing.JButton();
        BotonSalir = new javax.swing.JButton();
        BotonBaja = new javax.swing.JButton();
        BotonTratamiento = new javax.swing.JButton();
        BotonLiberacion = new javax.swing.JButton();
        BotonListado = new javax.swing.JButton();
        TextoDelTitulo = new javax.swing.JLabel();
        PanelDeContenido = new javax.swing.JPanel();
        PanelAlta = new javax.swing.JPanel();
        TituloAlta = new javax.swing.JLabel();
        LabelID = new javax.swing.JLabel();
        TextFieldID = new javax.swing.JTextField();
        LabelTipo = new javax.swing.JLabel();
        LabelNombre = new javax.swing.JLabel();
        TextFieldNombre = new javax.swing.JTextField();
        LabelEspecie = new javax.swing.JLabel();
        TextFieldEspecie = new javax.swing.JTextField();
        LabelPeso = new javax.swing.JLabel();
        TextFieldPeso = new javax.swing.JTextField();
        LabelTipoLesion = new javax.swing.JLabel();
        TextFieldTipoLesion = new javax.swing.JTextField();
        LabelGravedadLesion = new javax.swing.JLabel();
        TipoAnimalComboBox = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        LabelFechaEntrada = new javax.swing.JLabel();
        LabelVeterinario = new javax.swing.JLabel();
        TextFieldVeterinario = new javax.swing.JTextField();
        BotónGuardarAlta = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        BotonGravedadAlta = new javax.swing.JRadioButton();
        BotonGravedadBaja = new javax.swing.JRadioButton();
        TextFieldTratamientoInicial = new javax.swing.JTextField();
        PanelMotivoLesion = new javax.swing.JPanel();
        PanelLesionMamifero = new javax.swing.JPanel();
        MotivoAtropello = new javax.swing.JCheckBox();
        PanelLesionAve = new javax.swing.JPanel();
        MotivoCazaFurtiva = new javax.swing.JCheckBox();
        PanelLesionReptil = new javax.swing.JPanel();
        MotivoInfeccion = new javax.swing.JCheckBox();
        PanelListado = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        TipoListadoComboBoxPanelListado = new javax.swing.JComboBox<>();
        PanelJListListadoPanelListado = new javax.swing.JScrollPane();
        ListadoAnimales = new javax.swing.JList<>();
        BotonParaListarPanelListado = new javax.swing.JButton();
        PanelBaja = new javax.swing.JPanel();
        BotonParaBajaPanelBaja = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        BotonParaListarPanelBaja = new javax.swing.JButton();
        TipoListadoComboBoxPanelBaja = new javax.swing.JComboBox<>();
        PanelJListListadoPanelBaja = new javax.swing.JScrollPane();
        ListadoAnimalesPanelBaja = new javax.swing.JList<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        ListadoBajasPanelBaja = new javax.swing.JList<>();
        jLabel5 = new javax.swing.JLabel();
        PanelLiberacion = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        TipoListadoComboBox2 = new javax.swing.JComboBox<>();
        PanelJList2 = new javax.swing.JScrollPane();
        ListadoAnimales2 = new javax.swing.JList<>();
        BotonParaListar2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        PanelDeFondoGlobal.setBackground(new java.awt.Color(102, 153, 255));
        PanelDeFondoGlobal.setToolTipText("");
        PanelDeFondoGlobal.setPreferredSize(new java.awt.Dimension(1000, 700));
        PanelDeFondoGlobal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PanelDelMenu.setBackground(new java.awt.Color(102, 153, 0));
        PanelDelMenu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("MENÚ");
        PanelDelMenu.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, 118, 40));

        BotonAlta.setText("Alta");
        BotonAlta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonAltaActionPerformed(evt);
            }
        });
        PanelDelMenu.add(BotonAlta, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 140, -1));

        BotonSalir.setText("Salir");
        BotonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonSalirActionPerformed(evt);
            }
        });
        PanelDelMenu.add(BotonSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 460, 140, -1));

        BotonBaja.setText("Baja");
        BotonBaja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonBajaActionPerformed(evt);
            }
        });
        PanelDelMenu.add(BotonBaja, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 140, -1));

        BotonTratamiento.setText("Tratamiento");
        BotonTratamiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonTratamientoActionPerformed(evt);
            }
        });
        PanelDelMenu.add(BotonTratamiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 140, -1));

        BotonLiberacion.setText("Liberacion");
        BotonLiberacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonLiberacionActionPerformed(evt);
            }
        });
        PanelDelMenu.add(BotonLiberacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 250, 140, -1));

        BotonListado.setText("Listado");
        BotonListado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonListadoActionPerformed(evt);
            }
        });
        PanelDelMenu.add(BotonListado, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 300, 140, -1));

        PanelDeFondoGlobal.add(PanelDelMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 140, 700));

        TextoDelTitulo.setBackground(new java.awt.Color(255, 255, 255));
        TextoDelTitulo.setFont(new java.awt.Font("Jokerman", 0, 18)); // NOI18N
        TextoDelTitulo.setForeground(new java.awt.Color(255, 255, 255));
        TextoDelTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TextoDelTitulo.setText("CENTRO DE RECUPERACION DE ANIMALES SALVAJES");
        PanelDeFondoGlobal.add(TextoDelTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 0, 660, 60));

        PanelDeContenido.setLayout(new java.awt.CardLayout());

        TituloAlta.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        TituloAlta.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TituloAlta.setText("DAR DE ALTA");

        LabelID.setText("ID:");

        TextFieldID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextFieldIDActionPerformed(evt);
            }
        });

        LabelTipo.setText("TIPO:");

        LabelNombre.setText("NOMBRE:");

        LabelEspecie.setText("ESPECIE:");

        LabelPeso.setText("PESO:");

        LabelTipoLesion.setText("TIPO DE LESION:");

        LabelGravedadLesion.setText("GRAVEDAD DE LESION:");

        TipoAnimalComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mamífero", "Ave", "Reptil" }));
        TipoAnimalComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TipoAnimalComboBoxActionPerformed(evt);
            }
        });

        jLabel10.setText("MOTIVO DE LESION:");

        LabelFechaEntrada.setText("TRATAMIENTO INICIAL:");

        LabelVeterinario.setText("VETERINARIO:");

        BotónGuardarAlta.setText("GUARDAR");
        BotónGuardarAlta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotónGuardarAltaActionPerformed(evt);
            }
        });

        BotonGravedadAlta.setText("Alta");
        BotonGravedadAlta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonGravedadAltaActionPerformed(evt);
            }
        });

        BotonGravedadBaja.setText("Baja");
        BotonGravedadBaja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonGravedadBajaActionPerformed(evt);
            }
        });

        PanelMotivoLesion.setLayout(new java.awt.CardLayout());

        PanelLesionMamifero.setPreferredSize(new java.awt.Dimension(0, 22));

        MotivoAtropello.setText("Atropello");
        MotivoAtropello.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MotivoAtropelloActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelLesionMamiferoLayout = new javax.swing.GroupLayout(PanelLesionMamifero);
        PanelLesionMamifero.setLayout(PanelLesionMamiferoLayout);
        PanelLesionMamiferoLayout.setHorizontalGroup(
            PanelLesionMamiferoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 373, Short.MAX_VALUE)
            .addGroup(PanelLesionMamiferoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(PanelLesionMamiferoLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(MotivoAtropello)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        PanelLesionMamiferoLayout.setVerticalGroup(
            PanelLesionMamiferoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 22, Short.MAX_VALUE)
            .addGroup(PanelLesionMamiferoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(PanelLesionMamiferoLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(MotivoAtropello)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        PanelMotivoLesion.add(PanelLesionMamifero, "card2");

        PanelLesionAve.setPreferredSize(new java.awt.Dimension(0, 22));

        MotivoCazaFurtiva.setText("Caza Furtiva");
        MotivoCazaFurtiva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MotivoCazaFurtivaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelLesionAveLayout = new javax.swing.GroupLayout(PanelLesionAve);
        PanelLesionAve.setLayout(PanelLesionAveLayout);
        PanelLesionAveLayout.setHorizontalGroup(
            PanelLesionAveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 373, Short.MAX_VALUE)
            .addGroup(PanelLesionAveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(PanelLesionAveLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(MotivoCazaFurtiva)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        PanelLesionAveLayout.setVerticalGroup(
            PanelLesionAveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 22, Short.MAX_VALUE)
            .addGroup(PanelLesionAveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(PanelLesionAveLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(MotivoCazaFurtiva)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        PanelMotivoLesion.add(PanelLesionAve, "card3");

        PanelLesionReptil.setPreferredSize(new java.awt.Dimension(0, 22));

        MotivoInfeccion.setText("Infeccion Bacteriana");

        javax.swing.GroupLayout PanelLesionReptilLayout = new javax.swing.GroupLayout(PanelLesionReptil);
        PanelLesionReptil.setLayout(PanelLesionReptilLayout);
        PanelLesionReptilLayout.setHorizontalGroup(
            PanelLesionReptilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 373, Short.MAX_VALUE)
            .addGroup(PanelLesionReptilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(PanelLesionReptilLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(MotivoInfeccion)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        PanelLesionReptilLayout.setVerticalGroup(
            PanelLesionReptilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 22, Short.MAX_VALUE)
            .addGroup(PanelLesionReptilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(PanelLesionReptilLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(MotivoInfeccion)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        PanelMotivoLesion.add(PanelLesionReptil, "card4");

        javax.swing.GroupLayout PanelAltaLayout = new javax.swing.GroupLayout(PanelAlta);
        PanelAlta.setLayout(PanelAltaLayout);
        PanelAltaLayout.setHorizontalGroup(
            PanelAltaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelAltaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelAltaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelAltaLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PanelAltaLayout.createSequentialGroup()
                        .addGroup(PanelAltaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(PanelAltaLayout.createSequentialGroup()
                                .addComponent(LabelID)
                                .addGap(18, 18, 18)
                                .addComponent(TextFieldID))
                            .addGroup(PanelAltaLayout.createSequentialGroup()
                                .addComponent(LabelTipo)
                                .addGap(18, 18, 18)
                                .addComponent(TipoAnimalComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(PanelAltaLayout.createSequentialGroup()
                                .addComponent(LabelNombre)
                                .addGap(18, 18, 18)
                                .addComponent(TextFieldNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(PanelAltaLayout.createSequentialGroup()
                                .addComponent(LabelEspecie)
                                .addGap(18, 18, 18)
                                .addComponent(TextFieldEspecie))
                            .addGroup(PanelAltaLayout.createSequentialGroup()
                                .addComponent(LabelPeso)
                                .addGap(18, 18, 18)
                                .addComponent(TextFieldPeso)))
                        .addGap(98, 98, 98)
                        .addGroup(PanelAltaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PanelAltaLayout.createSequentialGroup()
                                .addComponent(LabelTipoLesion)
                                .addGap(18, 18, 18)
                                .addComponent(TextFieldTipoLesion))
                            .addGroup(PanelAltaLayout.createSequentialGroup()
                                .addComponent(LabelVeterinario)
                                .addGap(18, 18, 18)
                                .addComponent(TextFieldVeterinario))
                            .addGroup(PanelAltaLayout.createSequentialGroup()
                                .addComponent(LabelGravedadLesion)
                                .addGap(39, 39, 39)
                                .addComponent(BotonGravedadAlta)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 238, Short.MAX_VALUE)
                                .addComponent(BotonGravedadBaja)
                                .addGap(22, 22, 22))
                            .addGroup(PanelAltaLayout.createSequentialGroup()
                                .addGroup(PanelAltaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel10)
                                    .addComponent(LabelFechaEntrada))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(PanelAltaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(PanelMotivoLesion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(TextFieldTratamientoInicial)))))
                    .addComponent(TituloAlta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(PanelAltaLayout.createSequentialGroup()
                        .addGroup(PanelAltaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PanelAltaLayout.createSequentialGroup()
                                .addGap(279, 279, 279)
                                .addComponent(BotónGuardarAlta))
                            .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        PanelAltaLayout.setVerticalGroup(
            PanelAltaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelAltaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(TituloAlta, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelAltaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelID)
                    .addComponent(TextFieldID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabelTipoLesion)
                    .addComponent(TextFieldTipoLesion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PanelAltaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelTipo)
                    .addComponent(LabelGravedadLesion)
                    .addComponent(TipoAnimalComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BotonGravedadAlta)
                    .addComponent(BotonGravedadBaja))
                .addGap(18, 18, 18)
                .addGroup(PanelAltaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(PanelAltaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(LabelNombre)
                        .addComponent(TextFieldNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel10))
                    .addComponent(PanelMotivoLesion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(PanelAltaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelEspecie)
                    .addComponent(TextFieldEspecie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabelFechaEntrada)
                    .addComponent(TextFieldTratamientoInicial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PanelAltaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelPeso)
                    .addComponent(TextFieldPeso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabelVeterinario)
                    .addComponent(TextFieldVeterinario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(61, 61, 61)
                .addComponent(jSeparator2, javax.swing.GroupLayout.DEFAULT_SIZE, 215, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BotónGuardarAlta)
                .addGap(43, 43, 43))
        );

        PanelDeContenido.add(PanelAlta, "card2");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Listar Animales guardados");

        TipoListadoComboBoxPanelListado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Todos", "Mamífero", "Ave", "Reptil" }));
        TipoListadoComboBoxPanelListado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TipoListadoComboBoxPanelListadoActionPerformed(evt);
            }
        });

        PanelJListListadoPanelListado.setViewportView(ListadoAnimales);

        BotonParaListarPanelListado.setText("listar");
        BotonParaListarPanelListado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonParaListarPanelListadoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelListadoLayout = new javax.swing.GroupLayout(PanelListado);
        PanelListado.setLayout(PanelListadoLayout);
        PanelListadoLayout.setHorizontalGroup(
            PanelListadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelListadoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 491, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(TipoListadoComboBoxPanelListado, javax.swing.GroupLayout.PREFERRED_SIZE, 339, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addComponent(PanelJListListadoPanelListado)
            .addGroup(PanelListadoLayout.createSequentialGroup()
                .addGap(274, 274, 274)
                .addComponent(BotonParaListarPanelListado)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PanelListadoLayout.setVerticalGroup(
            PanelListadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelListadoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelListadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(TipoListadoComboBoxPanelListado)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(BotonParaListarPanelListado)
                .addGap(28, 28, 28)
                .addComponent(PanelJListListadoPanelListado, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(124, 124, 124))
        );

        PanelDeContenido.add(PanelListado, "card5");

        BotonParaBajaPanelBaja.setText("Dar de Baja");
        BotonParaBajaPanelBaja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonParaBajaPanelBajaActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Listar Animales guardados para dar de baja");

        BotonParaListarPanelBaja.setText("listar");
        BotonParaListarPanelBaja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonParaListarPanelBajaActionPerformed(evt);
            }
        });

        TipoListadoComboBoxPanelBaja.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Todos", "Mamífero", "Ave", "Reptil" }));
        TipoListadoComboBoxPanelBaja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TipoListadoComboBoxPanelBajaActionPerformed(evt);
            }
        });

        PanelJListListadoPanelBaja.setViewportView(ListadoAnimalesPanelBaja);

        jScrollPane1.setViewportView(ListadoBajasPanelBaja);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel5.setText("Animales dados de baja");

        javax.swing.GroupLayout PanelBajaLayout = new javax.swing.GroupLayout(PanelBaja);
        PanelBaja.setLayout(PanelBajaLayout);
        PanelBajaLayout.setHorizontalGroup(
            PanelBajaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelJListListadoPanelBaja)
            .addComponent(jScrollPane1)
            .addGroup(PanelBajaLayout.createSequentialGroup()
                .addGroup(PanelBajaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelBajaLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 491, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(TipoListadoComboBoxPanelBaja, javax.swing.GroupLayout.PREFERRED_SIZE, 339, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PanelBajaLayout.createSequentialGroup()
                        .addGroup(PanelBajaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PanelBajaLayout.createSequentialGroup()
                                .addGap(320, 320, 320)
                                .addComponent(BotonParaListarPanelBaja)
                                .addGap(88, 88, 88)
                                .addComponent(BotonParaBajaPanelBaja))
                            .addGroup(PanelBajaLayout.createSequentialGroup()
                                .addGap(97, 97, 97)
                                .addComponent(jLabel5)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        PanelBajaLayout.setVerticalGroup(
            PanelBajaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelBajaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelBajaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(TipoListadoComboBoxPanelBaja)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(PanelBajaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BotonParaListarPanelBaja)
                    .addComponent(BotonParaBajaPanelBaja))
                .addGap(28, 28, 28)
                .addComponent(PanelJListListadoPanelBaja, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(jLabel5)
                .addGap(41, 41, 41)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(138, 138, 138))
        );

        PanelDeContenido.add(PanelBaja, "card5");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Listar Animales guardados");

        TipoListadoComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Todos", "Mamífero", "Ave", "Reptil" }));
        TipoListadoComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TipoListadoComboBox2ActionPerformed(evt);
            }
        });

        PanelJList2.setViewportView(ListadoAnimales2);

        BotonParaListar2.setText("listar");
        BotonParaListar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonParaListar2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelLiberacionLayout = new javax.swing.GroupLayout(PanelLiberacion);
        PanelLiberacion.setLayout(PanelLiberacionLayout);
        PanelLiberacionLayout.setHorizontalGroup(
            PanelLiberacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelLiberacionLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 491, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(TipoListadoComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 339, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addComponent(PanelJList2)
            .addGroup(PanelLiberacionLayout.createSequentialGroup()
                .addGap(274, 274, 274)
                .addComponent(BotonParaListar2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PanelLiberacionLayout.setVerticalGroup(
            PanelLiberacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelLiberacionLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelLiberacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(TipoListadoComboBox2)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(BotonParaListar2)
                .addGap(28, 28, 28)
                .addComponent(PanelJList2, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(124, 124, 124))
        );

        PanelDeContenido.add(PanelLiberacion, "card5");

        PanelDeFondoGlobal.add(PanelDeContenido, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 60, 860, 640));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelDeFondoGlobal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelDeFondoGlobal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void BotonAltaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonAltaActionPerformed
        PanelDeContenido.removeAll();
        PanelDeContenido.add(PanelAlta);
        PanelDeContenido.repaint();
        PanelDeContenido.revalidate();
    }//GEN-LAST:event_BotonAltaActionPerformed

    private void BotonBajaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonBajaActionPerformed
        // TODO add your handling code here:
        PanelDeContenido.removeAll();
        PanelDeContenido.add(PanelBaja);
        PanelDeContenido.repaint();
        PanelDeContenido.revalidate();
    }//GEN-LAST:event_BotonBajaActionPerformed

    private void BotonTratamientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonTratamientoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BotonTratamientoActionPerformed

    private void BotonLiberacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonLiberacionActionPerformed
        // TODO add your handling code here:
        PanelDeContenido.removeAll();
        PanelDeContenido.add(PanelLiberacion);
        PanelDeContenido.repaint();
        PanelDeContenido.revalidate();
    }//GEN-LAST:event_BotonLiberacionActionPerformed

    private void BotonListadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonListadoActionPerformed
        // TODO add your handling code here:
        PanelDeContenido.removeAll();
        PanelDeContenido.add(PanelListado);
        PanelDeContenido.repaint();
        PanelDeContenido.revalidate();
    }//GEN-LAST:event_BotonListadoActionPerformed

    private void BotonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_BotonSalirActionPerformed

    private void TextFieldIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextFieldIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextFieldIDActionPerformed

    private void TipoAnimalComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TipoAnimalComboBoxActionPerformed
        // TODO add your handling code here:
        switch (TipoAnimalComboBox.getSelectedIndex()) {
            case 0: // Mamífero
                PanelLesionAve.setVisible(false);
                PanelLesionMamifero.setVisible(true);
                PanelLesionReptil.setVisible(false);
                break;
            case 1: // Ave
                PanelLesionAve.setVisible(true);
                PanelLesionMamifero.setVisible(false);
                PanelLesionReptil.setVisible(false);
                break;
            case 2: // Reptil
                PanelLesionAve.setVisible(false);
                PanelLesionMamifero.setVisible(false);
                PanelLesionReptil.setVisible(true);
                break;
        }
        PanelMotivoLesion.revalidate();
        PanelMotivoLesion.repaint();
    }//GEN-LAST:event_TipoAnimalComboBoxActionPerformed

    private void BotónGuardarAltaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotónGuardarAltaActionPerformed
        // TODO add your handling code here:
        // Obtener los valores de los campos
        String id = TextFieldID.getText();
        String tipo = TipoAnimalComboBox.getSelectedItem().toString();
        String nombre = TextFieldNombre.getText();
        String especie = TextFieldEspecie.getText();
        String peso = TextFieldPeso.getText();
        String tipoLesion = TextFieldTipoLesion.getText();
        String TratamientoInicial = TextFieldTratamientoInicial.getText();
        String gravedadLesion = BotonGravedadAlta.isSelected() ? "Alta" : "Baja";
        Date fechaEntrada = new Date();
        String veterinario = TextFieldVeterinario.getText();
        boolean motivoLesionAtropello = MotivoAtropello.isSelected();
        boolean motivoLesionCazaFurtiva = MotivoCazaFurtiva.isSelected();
        boolean motivoLesionInfeccionBacteriana = MotivoInfeccion.isSelected();

// Verificar si todos los campos están llenos
        if (tipo.equals("") || TratamientoInicial.equals("") || nombre.equals("") || especie.equals("") || peso.equals("") || tipoLesion.equals("") || gravedadLesion.equals("") || veterinario.equals("")) {
            JOptionPane.showMessageDialog(null, "Por favor, rellene todos los campos para guardar un nuevo animal.", "Campos incompletos", JOptionPane.WARNING_MESSAGE);
        } else {
            Animal animal = null;
            switch (tipo) {
                case "Mamífero":
                    animal = new Mamífero(motivoLesionAtropello, id, tipo, nombre, especie, peso, tipoLesion, gravedadLesion, fechaEntrada, TratamientoInicial, veterinario);
                    ((Mamífero) animal).setMotivoLesionAtropello(motivoLesionAtropello);
                    break;
                case "Ave":
                    animal = new Ave(motivoLesionCazaFurtiva, id, tipo, nombre, especie, peso, tipoLesion, gravedadLesion, fechaEntrada, TratamientoInicial, veterinario);
                    ((Ave) animal).setMotivoLesionCazaFurtiva(motivoLesionCazaFurtiva);
                    break;
                case "Reptil":
                    animal = new Reptil(motivoLesionInfeccionBacteriana, id, tipo, nombre, especie, peso, tipoLesion, gravedadLesion, fechaEntrada, TratamientoInicial, veterinario);
                    ((Reptil) animal).setMotivoLesionInfeccionBacteriana(motivoLesionInfeccionBacteriana);
                    break;
            }
            if (animal != null) {
                // Agregar el nuevo animal al ArrayList correspondiente
                switch (tipo) {
                    case "Mamífero":
                        listaMamíferos.add((Mamífero) animal);
                        break;
                    case "Ave":
                        listaAves.add((Ave) animal);
                        break;
                    case "Reptil":
                        listaReptiles.add((Reptil) animal);
                        break;
                }
                // Mostrar mensaje de éxito
                JOptionPane.showMessageDialog(null, "Animal guardado exitosamente.", "Guardado exitoso", JOptionPane.INFORMATION_MESSAGE);
                // Limpiar los campos
                TextFieldID.setText("");
                TextFieldNombre.setText("");
                TextFieldEspecie.setText("");
                TextFieldPeso.setText("");
                TextFieldTipoLesion.setText("");
                BotonGravedadAlta.setSelected(true);
                TextFieldTratamientoInicial.setText("");
                TextFieldVeterinario.setText("");
                MotivoAtropello.setSelected(false);
                MotivoCazaFurtiva.setSelected(false);
                MotivoInfeccion.setSelected(false);
            }
        }
    }//GEN-LAST:event_BotónGuardarAltaActionPerformed

    private void TipoListadoComboBoxPanelListadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TipoListadoComboBoxPanelListadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TipoListadoComboBoxPanelListadoActionPerformed

    private void MotivoAtropelloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MotivoAtropelloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MotivoAtropelloActionPerformed

    private void BotonGravedadAltaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonGravedadAltaActionPerformed
        // TODO add your handling code here:
        GrupoBotonesGravedadLesion.add(BotonGravedadAlta);
    }//GEN-LAST:event_BotonGravedadAltaActionPerformed

    private void BotonGravedadBajaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonGravedadBajaActionPerformed
        // TODO add your handling code here:
        GrupoBotonesGravedadLesion.add(BotonGravedadBaja);
    }//GEN-LAST:event_BotonGravedadBajaActionPerformed

    private void BotonParaListarPanelListadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonParaListarPanelListadoActionPerformed
        DefaultListModel modelo = new DefaultListModel();
        ListadoAnimales.setModel(modelo); //limpiamos el JList
        if (TipoListadoComboBoxPanelListado.getSelectedItem().toString().equals("Reptil")) {
            for (Reptil r : listaReptiles) {
                modelo.addElement(r.toString());
            }
        } else if (TipoListadoComboBoxPanelListado.getSelectedItem().toString().equals("Mamífero")) {
            for (Mamífero m : listaMamíferos) {
                modelo.addElement(m.toString());
            }
        } else if (TipoListadoComboBoxPanelListado.getSelectedItem().toString().equals("Ave")) {
            for (Ave a : listaAves) {
                modelo.addElement(a.toString());
            }
        } else { //Todos los animales
            for (Mamífero m : listaMamíferos) {
                modelo.addElement(m.toString());
            }
            for (Ave a : listaAves) {
                modelo.addElement(a.toString());
            }
            for (Reptil r : listaReptiles) {
                modelo.addElement(r.toString());
            }
        }
        ListadoAnimales.setModel(modelo);
    }//GEN-LAST:event_BotonParaListarPanelListadoActionPerformed

    private void MotivoCazaFurtivaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MotivoCazaFurtivaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MotivoCazaFurtivaActionPerformed

    private void TipoListadoComboBoxPanelBajaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TipoListadoComboBoxPanelBajaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TipoListadoComboBoxPanelBajaActionPerformed

    private void BotonParaListarPanelBajaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonParaListarPanelBajaActionPerformed
        DefaultListModel modelo = new DefaultListModel();
        ListadoAnimalesPanelBaja.setModel(modelo); //limpiamos el JList
        if (TipoListadoComboBoxPanelBaja.getSelectedItem().toString().equals("Reptil")) {
            for (Reptil r : listaReptiles) {
                modelo.addElement(r.toString());
            }
        } else if (TipoListadoComboBoxPanelBaja.getSelectedItem().toString().equals("Mamífero")) {
            for (Mamífero m : listaMamíferos) {
                modelo.addElement(m.toString());
            }
        } else if (TipoListadoComboBoxPanelBaja.getSelectedItem().toString().equals("Ave")) {
            for (Ave a : listaAves) {
                modelo.addElement(a.toString());
            }
        } else { //Todos los animales
            for (Mamífero m : listaMamíferos) {
                modelo.addElement(m.toString());
            }
            for (Ave a : listaAves) {
                modelo.addElement(a.toString());
            }
            for (Reptil r : listaReptiles) {
                modelo.addElement(r.toString());
            }
        }
        ListadoAnimalesPanelBaja.setModel(modelo);

    }//GEN-LAST:event_BotonParaListarPanelBajaActionPerformed

    private void TipoListadoComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TipoListadoComboBox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TipoListadoComboBox2ActionPerformed

    private void BotonParaListar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonParaListar2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BotonParaListar2ActionPerformed

    private void BotonParaBajaPanelBajaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonParaBajaPanelBajaActionPerformed
        // TODO add your handling code here:
        int index = ListadoAnimalesPanelBaja.getSelectedIndex();
        if (index != -1) {
            Animal animalSeleccionado = null;
            String animalString = ListadoAnimalesPanelBaja.getSelectedValue();
            for (Mamífero m : listaMamíferos) {
                if (m.toString().equals(animalString)) {
                    animalSeleccionado = m;
                    listaMamíferos.remove(m);
                    break;
                }
            }
            if (animalSeleccionado == null) {
                for (Ave a : listaAves) {
                    if (a.toString().equals(animalString)) {
                        animalSeleccionado = a;
                        listaAves.remove(a);
                        break;
                    }
                }
            }
            if (animalSeleccionado == null) {
                for (Reptil r : listaReptiles) {
                    if (r.toString().equals(animalString)) {
                        animalSeleccionado = r;
                        listaReptiles.remove(r);
                        break;
                    }
                }
            }
            if (animalSeleccionado != null) {
                animalSeleccionado.setFechaEntrada(new Date()); // Actualizar fecha de entrada del animal
                listaBajas.add(animalSeleccionado);
                DefaultListModel modeloBajas = new DefaultListModel();
                for (Animal a : listaBajas) {
                    modeloBajas.addElement(a.toString());
                }
                ListadoBajasPanelBaja.setModel(modeloBajas);
                DefaultListModel modeloAnimales = (DefaultListModel) ListadoAnimalesPanelBaja.getModel();
                modeloAnimales.remove(index);
            } else {
                JOptionPane.showMessageDialog(null, "Error al dar de baja el animal");
            }
        } else {
            JOptionPane.showMessageDialog(null, "Debe seleccionar un animal del listado de animales guardados para dar de baja");
        }

    }//GEN-LAST:event_BotonParaBajaPanelBajaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interfaz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonAlta;
    private javax.swing.JButton BotonBaja;
    private javax.swing.JRadioButton BotonGravedadAlta;
    private javax.swing.JRadioButton BotonGravedadBaja;
    private javax.swing.JButton BotonLiberacion;
    private javax.swing.JButton BotonListado;
    private javax.swing.JButton BotonParaBajaPanelBaja;
    private javax.swing.JButton BotonParaListar2;
    private javax.swing.JButton BotonParaListarPanelBaja;
    private javax.swing.JButton BotonParaListarPanelListado;
    private javax.swing.JButton BotonSalir;
    private javax.swing.JButton BotonTratamiento;
    private javax.swing.JButton BotónGuardarAlta;
    private javax.swing.ButtonGroup GrupoBotonesGravedadLesion;
    private javax.swing.JLabel LabelEspecie;
    private javax.swing.JLabel LabelFechaEntrada;
    private javax.swing.JLabel LabelGravedadLesion;
    private javax.swing.JLabel LabelID;
    private javax.swing.JLabel LabelNombre;
    private javax.swing.JLabel LabelPeso;
    private javax.swing.JLabel LabelTipo;
    private javax.swing.JLabel LabelTipoLesion;
    private javax.swing.JLabel LabelVeterinario;
    private javax.swing.JList<String> ListadoAnimales;
    private javax.swing.JList<String> ListadoAnimales2;
    private javax.swing.JList<String> ListadoAnimalesPanelBaja;
    private javax.swing.JList<String> ListadoBajasPanelBaja;
    private javax.swing.JCheckBox MotivoAtropello;
    private javax.swing.JCheckBox MotivoCazaFurtiva;
    private javax.swing.JCheckBox MotivoInfeccion;
    private javax.swing.JPanel PanelAlta;
    private javax.swing.JPanel PanelBaja;
    private javax.swing.JPanel PanelDeContenido;
    private javax.swing.JPanel PanelDeFondoGlobal;
    private javax.swing.JPanel PanelDelMenu;
    private javax.swing.JScrollPane PanelJList2;
    private javax.swing.JScrollPane PanelJListListadoPanelBaja;
    private javax.swing.JScrollPane PanelJListListadoPanelListado;
    private javax.swing.JPanel PanelLesionAve;
    private javax.swing.JPanel PanelLesionMamifero;
    private javax.swing.JPanel PanelLesionReptil;
    private javax.swing.JPanel PanelLiberacion;
    private javax.swing.JPanel PanelListado;
    private javax.swing.JPanel PanelMotivoLesion;
    private javax.swing.JTextField TextFieldEspecie;
    private javax.swing.JTextField TextFieldID;
    private javax.swing.JTextField TextFieldNombre;
    private javax.swing.JTextField TextFieldPeso;
    private javax.swing.JTextField TextFieldTipoLesion;
    private javax.swing.JTextField TextFieldTratamientoInicial;
    private javax.swing.JTextField TextFieldVeterinario;
    private javax.swing.JLabel TextoDelTitulo;
    private javax.swing.JComboBox<String> TipoAnimalComboBox;
    private javax.swing.JComboBox<String> TipoListadoComboBox2;
    private javax.swing.JComboBox<String> TipoListadoComboBoxPanelBaja;
    private javax.swing.JComboBox<String> TipoListadoComboBoxPanelListado;
    private javax.swing.JLabel TituloAlta;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    // End of variables declaration//GEN-END:variables
}
